powersimdata/data_access/csv_store.py
powersimdata/scenario/create.py
powersimdata/scenario/execute.py
powersimdata/scenario/move.py

Fix docstring references to new `DataAccess` location, to fix references that were broken via https://github.com/Breakthrough-Energy/PowerSimData/pull/367.
No code, only docstring changes.
2 minutes

doc: fix docstring reference to new DataAccess location

---

powersimdata/scenario/scenario.py

Write method to retrieve the scenario table within the scenario framework
Return the scenario table as a data frame
```
(PostREISE) [~/CEM/PostREISE] (develop) brdo$ python
Python 3.8.3 (default, Jul  8 2020, 14:27:55) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from powersimdata.scenario.scenario import Scenario
>>> s = Scenario(1270)
Transferring ScenarioList.csv from server
100%|########################################################################################################################| 238k/238k [00:00<00:00, 1.54Mb/s]
Transferring ExecuteList.csv from server
100%|#######################################################################################################################| 21.5k/21.5k …
```

Add method to retrieve scenario table

---

powersimdata/data_access/tests/test_execute_csv.py
powersimdata/data_access/tests/test_scenario_csv.py

Fix failing integration test - id column is now an index, so isn't in the `.columns` attribute. Code changes were introduced in #365
Updated the expected list of column headers
Ran `pytest -m "not db"` locally
2 min

test: remove index column from test assertion

---

powersimdata/scenario/execute.py

Update scenario status before launching a simulation.
Update the `_scenario_status` attribute of the `Execute`.
The `_update_scenario_status` method is invoked in the `_check_if_ready` method which, in turn, is invoked in the `launch_simulation` method
2 min

Update scenario status

---

powersimdata/scenario/analyze.py

Restore previous functionality when calling `scenario.state.get_load_shed()` on a scenario with no load shed.
Change which Exception triggers the construction of an empty load_shed data frame.
Can be verified by calling `Scenario(1861).state.get_load_shed()` before and after.
2 minutes.

fix: change caught Exception for get_load_shed

---

powersimdata/design/investment/investment_costs.py

A FutureWarning is raised when running the tests:
```
powersimdata/design/investment/tests/test_investment_costs.py::test_calculate_gen_inv_costs_2030
/Users/brdo/CEM/PowerSimData/powersimdata/design/investment/investment_costs.py:371: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
cost["value"] = cost["value"].str.replace("$", "")
```
I have set the `regex` parameter to `True` in the `replace` method (current default value) to avoid any surprise when we update pandas.
No more warning when running `pytest`
The optional parameter `regex` is set to `True`, which is the current default value
2 min

Set keyword value

---

powersimdata/tests/mock_analyze.py

[Pull Request Etiquette doc](https://github.com/Breakthrough-Energy/REISE/wiki/Pull-Request-Etiquette)
Current MockScenario can't deal with storage tests, which is needed in [#201](https://github.com/Breakthrough-Energy/PostREISE/pull/201)
Add storage_pg entry to MockAnalyze object.
`/PowerSimData/powersimdata/tests/mock_analyze.py
`
1min

feat: add storage_pg entry to MockAnalyze

---

powersimdata/input/tests/test_transform_grid.py
powersimdata/input/transform_grid.py

Fix an Exception that's thrown when you add two new buses with the same coordinates.
In `TransformGrid` the `latlon2sub` variable holds a dictionary of `{(lat, lon): list_of_substation_ids}`. When we add a bus at a new location, we create a new substation, and we want to add its id to this lookup dict, but we had been adding it as an int, rather than a list containing that int.
**test_transform_grid** is updated to check for this bug.
The unit test is updated to check for this bug, and after the fix all tests pass again.
2 minutes.

fix: correct bug with repeated substation in TransformGrid._add_bus

---

powersimdata/design/investment/README.md

Update the README in the investment cost folder (this got missed in https://github.com/Breakthrough-Energy/PowerSimData/pull/297).
No code.
15 minutes.

doc: update investment cost README for current calculations

---

powersimdata/scenario/execute.py

Add a method to check the status endpoint in the reisejl api. This is provided for docker users to get more detailed output without having a separate shell in the server container. 
Other than the new method, added some basic validation on the deployment mode in the extract call since we have it defaulted to automatic when launched via the api.
Manual testing. Built the containers, launched a simulation, called `check_progress`. 
5 min
Note: I am not that excited to have the environment dependent functionality here, but plan on consolidating it in the future, and keeping it limited.

feat: add method to check progress of ongoing simulation

---

powersimdata/input/input_data.py
powersimdata/input/tests/test_transform_profile.py
powersimdata/input/transform_profile.py
powersimdata/network/usa_tamu/constants/zones.py

Use the newly constructed profiles:
* ***demand_vJan2021.csv***
* ***hydro_vJan2021.csv***
* ***solar_vJan2021.csv***
* ***wind_vJan2021.csv***
The power output in these profiles are now normalized (independent of the `Pmax` of the generator) and enclose, for each fuel type, all the generator in the US grid.
* Modify the `InputData` class to fetch the new profile located in **raw/GRID_MODEL*** where ***GRID_MODEL*** indicates the grid model, e.g., `usa_tamu`.
* Add a new dictionary in the `powersimdata.network.usa_tamu.constants.zones` to map interconnect to load zone id
* Refactor the `TransformProfile` class and the associated tests
run `pytest -v powersimdata/input/tests/test_transform_profile.py`. All the new profiles will be downloaded from the server the first time you run the …

Load and transform US normalized profiles

---

powersimdata/input/abstract_grid.py
powersimdata/input/change_table.py
powersimdata/input/grid.py
powersimdata/input/tests/test_change_table.py
powersimdata/input/tests/test_transform_grid.py
powersimdata/input/transform_grid.py
powersimdata/network/usa_tamu/constants/__init__.py
powersimdata/network/usa_tamu/constants/storage.py
powersimdata/network/usa_tamu/usa_tamu_model.py

Let user specify more parameters for storage. Closes #380.
- In **abstract_grid.py**: we add parameters `LossFactor`, `terminal_min`, and `terminal_max`.
- In **change_table.py**: we refactor `add_storage_capacity` to follow the pattern set in `add_plant` etc.
- In **grid.py**: ~we add the `Lossfactor` parameter to the ignored keys for `grid.storage` in the grid equality check.~ we automatically populate the ignored keys for grid.storage in the grid equality check from the new **storage.py**.
- In **transform_grid.py**: we interpret the new change table schema.
- We add a new file **storage.py** to handle `usa_tamu` storage constants.
- In **usa_tamu_model.py**: we get our storage default values from the new **storage.py** file.
- We update **test_change_table.py** and …

feat: let user specify more parameters for storage

---

powersimdata/input/input_data.py
powersimdata/output/output_data.py
powersimdata/scenario/analyze.py
powersimdata/scenario/create.py
powersimdata/scenario/helpers.py

Per discussion in https://github.com/Breakthrough-Energy/PowerSimData/pull/375, remove a redundant function. `get_bus_demand` is the fastest of the three identical functions:
```python
>>> import timeit
>>> from postreise.analyze.transmission.congestion import map_demand_to_buses
>>> from powersimdata.input.input_data import get_bus_demand
>>> from powersimdata.scenario.helpers import calculate_bus_demand
>>> from powersimdata.scenario.scenario import Scenario
>>> scenario = Scenario(824)
>>> demand = scenario.state.get_demand()
>>> grid = scenario.state.get_grid()
>>> bus = grid.bus
>>> timeit.timeit(lambda: map_demand_to_buses(grid, demand), number=10)
75.39155149999999
>>> timeit.timeit(lambda: calculate_bus_demand(bus, demand), number=10)
45.56884489999993
>>> timeit.timeit(lambda: …
```

refactor: remove redundant function for getting bus demand

---

Dockerfile
powersimdata/data_access/context.py
powersimdata/design/transmission/tests/test_statelines.py
powersimdata/input/tests/test_grid.py
powersimdata/scenario/execute.py
powersimdata/utility/tests/test_distance.py
tox.ini

We can take advantage of isort's built in "profile" for black compatibility. This includes a line length option which we were msising, along with a couple others I'm not sure about. [Source](https://github.com/PyCQA/isort/blob/develop/isort/profiles.py) from their repo is easy to read.
Added isort section in tox.ini
Ran `tox -e format` locally, and ci passes.
5 min

ci: use black profile for isort

---

powersimdata/utility/helpers.py

Allow the use of the `with` statement with the `PrintManager`.
`__enter__` and `__exit__` functions are added, as documented in https://docs.python.org/3/reference/compound_stmts.html#the-with-statement.
Previously, if we wanted to block print for a block of code, we needed to do something like:
```python
>>> pm = PrintManager()
>>> pm.block_print()
>>> demand = scenario.state.get_demand()
>>> pm.enable_print()
```
Now, the same commands can be accomplished via a shorter syntax:
```python
>>> with PrintManager():
...     demand = scenario.state.get_demand()
```
5 minutes.

feat: add with syntax to PrintManager

---

powersimdata/design/investment/const.py
powersimdata/design/investment/tests/test_investment_costs.py

Allow investment costs to be calculated for nuclear generators.
The functional change is in **const.py**: the set `gen_inv_cost_techdetails_to_keep` defines the only entries to keep from the NREL ATB data, and none of the existing ones cover nuclear. The category `"*"` covers nuclear and nuclear only, so there should be no side effects.
The changes in **test_investment_costs.py** are primarily to create a test for nuclear (the changes to `mock_plant` and `test_calculate_gen_inv_costs_2030`), and secondarily to clean up the code to make it a bit more readable.
The first commit adds the test, which will fail. The second commit implements the fix and the tests pass.
5 minutes.

fix: calculate investment cost for nuclear generators

---

powersimdata/design/generation/clean_capacity_scaling.py
powersimdata/design/generation/cost_curves.py
powersimdata/design/generation/tests/test_cost_curves.py
powersimdata/design/scenario_info.py
powersimdata/design/tests/test_scenario_info.py
powersimdata/design/transmission/tests/test_upgrade.py
powersimdata/design/transmission/upgrade.py
powersimdata/input/grid.py
powersimdata/network/model.py
powersimdata/network/usa_tamu/constants/zones.py
powersimdata/network/usa_tamu/model.py
powersimdata/tests/mock_scenario_info.py

- Generalize `area_to_loadzone` to be independent of any given grid model, and create model-specific helper functions which wrap around this generalized function.
- To accomplish this, add a `get_grid_model` function to the Grid object, which can work for a fresh `Grid` or for a `ScenarioGrid`. 
- `area_to_loadzone` is removed from `powersimdata.network.usa_tamu.model`.
- A generalized `area_to_loadzone` is added to `powersimdata.network.model`. We add `grid_model` and `mappings` as inputs, used to look up the constants from the appropriate grid model and to control which entries from `[grid_model].constants.zones` we try to access, so that we can avoid trying to access e.g. `zones["state2loadzone"` for a Europe grid.
- We pre-code the set of mapping methods within …

refactor: generalize area to loadzone

---

powersimdata/design/generation/curtailment.py
powersimdata/design/generation/tests/test_curtailment.py

Add functionality to pre-calculate curtailment caused by temporal mismatch between demand, inflexible generation, and curtailable profile resources.
First, profiles for hydro, solar, and wind are summed by type, with the exclusion of any plant IDs which the user specifies do not behave like all the rest (e.g., maybe some solar plants are behind-the-meter and are not curtailable, and we would want to see how this impact the rest of the wind plants).
Then, a time-series of inflexible generation is built-up, first based on on per-generator-type logic for plants without plant-level overrides (default values mimic what REISE.jl does currently), then based on the behavior of plant-level overrides.
Finally, the summed profile of curtailable resources is compared against the demand minus firm …

feat: add temporal curtailment calculation

---

powersimdata/scenario/execute.py

Corresponding changes for the new solver option in REISE.jl. This allows a user to specify either gurobi or glpk when launching a simulation, which closes the loop Daniel started by allowing multiple solvers. 
Expose the solver parameter which defaults to gurobi. This is passed to both the server and container "launch" methods for consistency.
Built the container and tested the solver argument in "container mode". This didn't invoke the `_launch_on_server` overload but it's essentially copy paste (same logic is used by the [api](https://github.com/Breakthrough-Energy/REISE.jl/blob/develop/pyreisejl/utility/app.py#L38) when launched via http)
5 min

feat: add optional solver parameter to launch_simulation

---

powersimdata/input/tests/test_transform_grid.py
powersimdata/input/transform_grid.py

Fix the bug, where new renewable generators added after a thermal generator inherit the thermal generator's cost curve coefficients.
The first commit reproduces the code in a test, the second commit fixes it by ensuring that no values are carried over.
1 minute.

fix: correct bug with carried-over gencosts for new plants

---

powersimdata/input/case_mat.py
powersimdata/scenario/execute.py

Decouple the matfile generation from the client/server setup. Closes #364.
Code doesn't functionally change, it's just reorganized.
Not tested yet to prepare a scenario, but tested for creating a matfile from a base grid.
```
>>> from powersimdata.input.grid import Grid
>>> from powersimdata.scenario.helpers import export_case_mat
>>> grid = Grid('Texas')
Reading bus.csv
Reading plant.csv
Reading gencost.csv
Reading branch.csv
Reading dcline.csv
Reading sub.csv
Reading bus2sub.csv
Reading zone.csv
>>> export_case_mat(grid, "dummy.mat")
```
5 minutes to understand, maybe longer to decide exactly where you think this should live.

refactor: move generation of matfile to separate function

---

powersimdata/tests/mock_grid.py
powersimdata/tests/mock_scenario.py

Add grid model information in mock objects
The scenario info dictionary is updated in the `MockScenario` class and the `Grid` class can be instantiated with an optional `model` parameter (default to `usa_tamu`)
All tests pass
`MockGrid` and `MockScenario` classes
5 min

Refactor mock objects

---

powersimdata/design/generation/clean_capacity_scaling.py
powersimdata/design/transmission/upgrade.py
powersimdata/input/grid.py

Return grid model for ScenarioGrid, reduce repeated get_grid_model calls
The first commit in **grid.py** fixes a bug where the grid model is determined but not returned.
The next commits in **clean_capacity_scaling.py** and **upgrade.py** move the `Grid.get_grid_model()` call out of a loop, since every call to `get_grid_model()` for a `ScenarioGrid` requires a fresh download of the ScenarioList to complete the `ScenarioListManager.get_scenario` call.
5 minutes.

fix/refactor: return grid model for ScenarioGrid, reduce repeated get_grid_model calls

---

powersimdata/data_access/csv_store.py
powersimdata/data_access/data_access.py
powersimdata/data_access/execute_list.py
powersimdata/data_access/scenario_list.py
powersimdata/data_access/tests/test_execute_csv.py
powersimdata/data_access/tests/test_execute_table.py
powersimdata/data_access/tests/test_scenario_csv.py
powersimdata/data_access/tests/test_scenario_table.py
powersimdata/scenario/delete.py
powersimdata/scenario/execute.py
powersimdata/scenario/move.py
powersimdata/utility/server_setup.py
setup.py

Supports local usage on windows by limiting the assumption of a unix environment to the `SSHDataAccess` class (in the context of scenario/execute list only; there is more work to do for full windows support)
Implements the following pattern for scenario/execute list operations. For local environments: just modify and query using pandas. For the client/server environment:
* calculate `sha1sum` prior to download and save in a local variable
* download the file and modify as needed
* upload the file
* using `flock` to synchronize access, check if the current `sha1sum` of the file is the same as before, and if so, write the changes and create a backup (the `-b` option on `mv` command). 
The client/server operation basically extends the local variant by adding the integrity check, so we get …

Manage scenario/execute list using pandas

---

powersimdata/input/input_data.py
powersimdata/scenario/create.py
powersimdata/scenario/tests/test_create.py

Fixes a couple of bugs when trying to get bus_demand from a Scenario in Create state. Closes #421.
- **test_create.py** adds a test that initially fails.
- In **create.py**, we ensure that the `scenario_info` gets updated before we call `get_bus_demand`.
- In **input_data.py**, we ensure that we only try to apply demand for the zones that are in this particular Grid.
The automated tests don't cover this, because getting the demand profiles requires ssh, but you can check that tests pass locally using `python -m pytest`.
5 minutes.

fix: ensure that get_bus_demand works in Create state

---

powersimdata/data_access/data_access.py
powersimdata/data_access/profile_helper.py
powersimdata/data_access/tests/test_profile_helper.py
powersimdata/input/input_data.py
powersimdata/input/tests/test_input_data.py
powersimdata/input/transform_profile.py
powersimdata/scenario/create.py
powersimdata/scenario/move.py
powersimdata/utility/server_setup.py

Use blob storage as the source for profiles, downloading as needed. 
Added a [version.json](https://bescienceswebsite.blob.core.windows.net/profiles/version.json) file to support listing available versions. The profiles are in the `raw/usa_tamu` folder in the blob container to mimic the structure elsewhere. Similar to before, we download if it doesn't exist locally. 
Deleted local copies of the profiles and ran a simulation using plug, which shows the files being downloaded (during the call to `prepare_simulation_input`). 
Example query (no change in usage, other than switching to static method)
```
In [18]: InputData.get_profile_version("usa_tamu", "solar")
Out[18]: ['vJan2021']
```
Snippet of files being downloaded
```
In [7]: scenario.state.prepare_simulation_input() …
```

Download profiles from blob storage

---

powersimdata/__init__.py
powersimdata/scenario/analyze.py
powersimdata/scenario/create.py
powersimdata/scenario/delete.py
powersimdata/scenario/execute.py
powersimdata/scenario/move.py
powersimdata/scenario/scenario.py
powersimdata/scenario/state.py
powersimdata/scenario/tests/test_create.py

Improve usability of the main framework classes (`Scenario` and `Grid`). Closes #418.
- The Scenario can now be instantiated with no arguments (`Scenario()`)
- The `Scenario` and `Grid` objects are imported into the name namespace, so that we can do something like:
```python
import powersimdata as psd
scenario = psd.Scenario()
```
- The state methods can be accessed from the Scenario object (`scenario.create_scenario()` maps to `scenario.state.create_scenario()`, if the scenario is in `create` state).
```python
>>> import powersimdata as psd
>>> scenario = psd.Scenario()
>>> scenario.create_scenario()
-------------------
MISSING INFORMATION
-------------------
plan
name
grid_model
interconnect
base_demand
base_hydro
base_solar
base_wind
change_table
start_date
end_date
interval
engine
>>> …
```

refactor: improve usability of Scenario object

---

powersimdata/scenario/execute.py

We introduced a bug in #406 where the "case_storage.mat" file is generated but not actually sent to the server and therefore not used in the simulation engine.
Tested that this fixes the bug, and **case_storage.mat** gets uploaded to the server where previous scenarios run with the exact same script don't have it.
5 minutes.

fix: upload storage matfile to server

---

README.md
powersimdata/design/generation/cost_curves.py
powersimdata/design/generation/tests/test_cost_curves.py

This change updates the cost curve visualization variable names to be more descriptive.
No functionality is changed. The refactored code still offers the ability to visualize and explore generator supply curves.
I updated the tests in `powresimdata/design/generation/tests/test_cost_curves.py` and they pass. I also double checked the outputs with an old demo notebook and the outputs remained the same.
The refactor is contained within `powersimdata/design/generation/cost_curves.py` and `powersimdata/design/generation/tests/test_cost_curves.py`. I also updated `README.md` to reflect the changes.
This should be pretty quick.

Update variable names for cost curve visualization

---

README.md
powersimdata/design/generation/cost_curves.py
powersimdata/design/generation/tests/test_cost_curves.py
powersimdata/design/investment/const.py
powersimdata/design/investment/create_mapping_files.py
powersimdata/design/investment/investment_costs.py
powersimdata/design/transmission/tests/test_upgrade.py
powersimdata/input/tests/test_change_table.py
powersimdata/utility/distance.py
tox.ini

Add pep8-naming check to flake8, so it is run by tox locally and in github. 
See https://github.com/Breakthrough-Energy/RenewableEnergyProject/issues/343
In this case, we ignore almost all the warnings. Note: adding the noqa on some lines also caused black to reformat into multi line declarations, which in turn requires moving the noqa back to the first line in that group. Hopefully we don't have to do this a lot. 
`tox -e flake8`
5 min

ci: add pep8-naming check to flake8 and ignore a bunch of warnings

---

powersimdata/design/investment/create_mapping_files.py
powersimdata/design/investment/investment_costs.py
powersimdata/scenario/analyze.py
powersimdata/scenario/create.py

Fix and improve docstrings
10 min

docs: fix and improve docstrings

---

README.md
docs/capacity_planning.rst
docs/grid.rst
docs/index.rst
docs/scenario.rst
docs/scenario_design.rst

Move sections of README in ReST files located in a new **docs** folder and rewrite README.
There is no code
I have checked that the content of the **powersimdata/docs** folder is properly display in our docs. To reproduce, checkout this branch and the `ben/powersimdata` branch in the ***docs*** repo and run `tox` there to make sure that the PowerSimData tutorial displays correctly
The content of the ReST files is almost identical to the sections in the current README. The only changes I made are:
* change code snippet to use #420 
* rearrange subsections in the scenario framework section to have create --> execute --> analyze --> delete --> move
The new README is the file that requires …

Rewrite README

---

powersimdata/data_access/csv_store.py
powersimdata/data_access/data_access.py
powersimdata/data_access/execute_list.py
powersimdata/data_access/profile_helper.py
powersimdata/data_access/scenario_list.py
powersimdata/data_access/tests/test_scenario_csv.py
powersimdata/scenario/create.py

Address #426 
Reduce the window when files could be corrupted by doing the following:
* When downloading a file, save to a temp file first, then move to destination.
* When uploading the scenario/execute list, first copy to a temp file and send that copy to the server
* Move scenario id generation into the `add_entry` method which should be atomic due to the checksum verification. This prevents a possible race condition of multiple scenarios with the same id being written to the server
Ran the demo and tests in plug. Also ran the same demo, up to `prepare_simulation_input` using the client/server container setup  (which uses the `SSHDataAccess` implementation). Things should at least still work for a single process, but could use more evidence that behavior is improved when multiple …

Reduce chance of concurrency issues

---

powersimdata/data_access/tests/test_profile_helper.py

The test currently fails on Windows, because it assumes a certain path format.
```python
__________________________ test_get_file_components ___________________________
def test_get_file_components():
s_info = {"base_wind": "v8", "grid_model": "europe"}
file_name, from_dir = ProfileHelper.get_file_components(s_info, "wind")
assert "wind_v8.csv" == file_name
>       assert "raw/europe" == from_dir
E       AssertionError: assert 'raw/europe' == 'raw\\europe'
E         - raw\europe
E         ?    ^
E         + raw/europe
E         ?    ^
powersimdata\data_access\tests\test_profile_helper.py:24: AssertionError
```
10 seconds.

fix: use os-specific path join for testing

---

powersimdata/scenario/scenario.py
powersimdata/scenario/tests/test_scenario.py

Add a test to check a bug for when we try to get a Scenario that isn't in the ScenarioList, and then fix the bug. This bug was introduced in https://github.com/Breakthrough-Energy/PowerSimData/pull/420.
We raise a `ValueError` before a `RecursionError` would be created (the previous bug).
Unit test finds the error before (or crashed python), and confirms that the fix works.
5 minutes.

Correct bug for Scenario init with bad descriptor

---

powersimdata/utility/helpers.py
powersimdata/utility/tests/test_helpers.py

Addresses #443.
Add a deepcopy on the way into the cache, so any modifications to the first returned object don't affect the object in the cache.
```python
>>> from powersimdata import Grid
>>> grid1 = Grid("Texas")
Reading bus.csv
Reading plant.csv
Reading gencost.csv
Reading branch.csv
Reading dcline.csv
Reading sub.csv
Reading bus2sub.csv
Reading zone.csv
>>> grid1.plant.groupby("type").sum().Pmax
type
coal       14501.59
hydro        555.10
ng         68642.42
nuclear     5138.60
solar       2460.20
wind       19062.63
Name: Pmax, dtype: float64
>>> grid1.plant.Pmax = 0
>>> grid1.plant.groupby("type").sum().Pmax
type
coal       0
hydro      0
ng         0
nuclear    0
solar      0
wind       0
Name: Pmax, dtype: int64
>>> grid2 = Grid("Texas")
>>> …
```

fix: add deepcopy on the way into MemoryCache

---

powersimdata/data_access/csv_store.py
powersimdata/data_access/data_access.py

Small fixes for issues with the temp files
In `data_access.py` - wait til after the context manager to remove the file, so it won't be in use by paramiko
In `csv_store.py`  - delete the temp file if necessary. This prevents leftover copies generated by tests, and within containers (anything using `LocalDataAccess`, which does a no-op for it's `.push` method). 
Only verified the temp file cleanup, hoping the other part is safe enough 
5 min

fix: cleanup temp file and fix PermissionError when file is in use

---

powersimdata/data_access/csv_store.py
powersimdata/data_access/data_access.py

Fix the PermissionsErrors we had been getting on Windows.
After writing to the tempfile, we tell the os to close the file before we try to do anything with it (e.g. move, delete). I got this from this stackoverflow post: https://stackoverflow.com/questions/34716996/cant-remove-a-file-which-created-by-tempfile-mkstemp-on-windows
Tests on Windows now pass, and I've successfully tested that this can create/prepare/launch a scenario on the server (previously had been failing so I fell back to the 'v0.4.1' branch).
Previously all **test_execute_csv** and **test_scenario_csv** tests failed with an error like:
`PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\DanielOlsen\\ScenarioData\\tmpmvu_jnyl'`
5-15 minutes, depending …

fix: close temp file before trying to move/delete

---

powersimdata/input/change_table.py

Add details to the docstrings of the ChangeTable methods for adding new elements, and update the main ChangeTable docstring to more accurately reflect the new storage schema (clean-up after https://github.com/Breakthrough-Energy/PowerSimData/pull/383).
Closes #445.
No code, just docstrings.
5-10 minutes.

doc: update ChangeTable docstrings

---

powersimdata/design/investment/investment_costs.py
powersimdata/design/investment/tests/test_investment_costs.py
powersimdata/input/change_table.py
powersimdata/tests/mock_grid.py

- As originally mentioned in https://github.com/Breakthrough-Energy/PowerSimData/pull/297, fix AC investment cost calculations so that we don't use underground line costs when not appropriate (lines of appropriate rating.voltage that are entirely within `NEISO` and `NYISO J-K` regions).
- Add tests of individual element cost calculations, which illustrate some bugs (e.g. branches within the `SOCO` [Southern Company] region were getting `NaN` cost estimates, and underground line costs were being applied inappropriately to some branches).
- Fix the bugs.
- Cleanup from https://github.com/Breakthrough-Energy/PowerSimData/pull/391, where we enabled the cost calculation of nuclear generators, but didn't ensure that costs would be calculated for costs cases other than `"Moderate"`.
These code …

fix: ensure that per-element investment cost are calculated accurately

---

powersimdata/data_access/data_access.py
powersimdata/scenario/execute.py

Breaking the refactoring to support native windows users into smaller chunks. This one simply defines the `DataAccess.makedir` method separately for local/ssh subclasses. 
Change `mkdir` command to `os.makedirs` for local calls. 
Ran `prepare_simulation_input()` on new scenario in fresh container. The code used for the server is the same as before.
5 min

feat: change makedir implementation to be os agnostic

---

powersimdata/design/transmission/upgrade.py

Allow user to prioritize branch upgrades based on estimated cost in the numerator (where the denominator remains the congestion shadow price at a certain quantile). See https://github.com/Breakthrough-Energy/PowerSimData/issues/439 for details.
The main logic is in the `if method == "cost":` block: we calculate the cost of upgrading each of the congested branches by 1x their original value, and then we divide the congestion metric by these values to get the branch upgrade ranking.
We also do a little simplification of the code where we calculate the bidirectional congestion, and move the application of the `composite_allow_list` filter up higher for better efficiency (so that we don't calculate quantiles for branches we know we're not going to select anyway), but these should have no …

feat: add 'cost' method to upgrade prioritization

---

powersimdata/data_access/data_access.py
powersimdata/utility/helpers.py

Small chunk of work to support windows natively. This one splits the file existence check, (basically an `ls` command) into one for `LocalDataAccess` which is os independent, and the one for `SSHDataAccess` which remains unchanged. 
Split implementation from base class, and some related cleanup.
Ran through creating and preparing a scenario in a container, so we exercise the base functionality and local implementation. Again, the server use case is not changed.
5 min

feat: os agnostic file existence check

---

powersimdata/design/investment/investment_costs.py

I found a new bug, where if you try to calculate AC investment costs for a scenario where at least one branch is connected to a new bus, we run into an error. Traceback, using Scenario 3828:
```python
c:\python38\lib\site-packages\powersimdata\design\investment\investment_costs.py in calculate_ac_inv_costs(scenario, sum_results, exclude_branches)
63         grid_new.branch.drop(index=present_exclude_branches, inplace=True)
64 
---> 65     costs = _calculate_ac_inv_costs(grid_new, sum_results)
66     return costs
67 
c:\python38\lib\site-packages\powersimdata\design\investment\investment_costs.py in _calculate_ac_inv_costs(grid_new, sum_results)
181     branch = grid_new.branch
182     branch.loc[:, "kV"] = bus.loc[branch.from_bus_id, "baseKV"].tolist()
--> 183     branch.loc[:, …
```

fix: enable AC investment costs to be calculated for branches connected to new buses

---

powersimdata/design/transmission/mwmiles.py
powersimdata/design/transmission/tests/test_mwmiles.py
powersimdata/scenario/create.py
powersimdata/scenario/scenario.py

- Allow MW-miles calculations to be done on scenarios in Create state (closes #457).
- Include new branches in calculations of MW-miles (closes #458).
- ~Allow branches not in the base grid to be scaled via the change table.~ **EDIT**: removed. See comment: https://github.com/Breakthrough-Energy/PowerSimData/pull/463#issuecomment-826925439
- In **create.py** and **scenario.py**: we add the `info` parameter to the `Scenario` (see #457 for a discussion).
- ~In **transform_grid.py**: we move branch and DC line scaling after branch and DC line additions, to enable scaling of newly-added branches (we could equivalently scale the entries in `"new_branch"` and "`new_dcline"`, but this way allows `scale_congested_mesh_branches` to continue to work without modifications even when it identifies …

feat: improve flexibility of MW-miles calculation, for Create state and new branches

---

powersimdata/design/investment/investment_costs.py
powersimdata/design/investment/tests/test_investment_costs.py
powersimdata/design/transmission/upgrade.py

- Update docstrings to reflect latest code details (which already include inflation calculations).
- In **investment_costs.py**: Most of the changes are docstrings, adding info that the costs are automatically brought to today using the inflation calculations. The other changes are that when we don't sum all costs together, we now return a single Series containing the cost data, rather than a data frame (the current practice for gen costs and ac costs) with many columns, one of which is `"Cost"` (AC line calculations) or `"CAPEX_total"` (plant calculations). This should be more intuitive for the user, who shouldn't have to wade through many unrelated columns when they are really just …

doc/refactor: improve documentation and usability of investment costs

---

.github/ISSUE_TEMPLATE/bug_report.md

This is the automatic **Bug Report Issue Template** from GitHub. I did not write anything. We can change it. Pandas has a template that is quite nice (see https://github.com/pandas-dev/pandas/issues/new/choose)

chore: create bug report issue template

---

powersimdata/input/change_table.py
powersimdata/input/tests/test_transform_grid.py
powersimdata/input/transform_grid.py

Allow scaling to be applied to elements that are added (i.e., not in the base grid). Closes #464.
We separate the scaling functions into scaling-by-zone and scaling-by-ID. We apply scaling-by-zone, then additions, then scaling-by-ID.
Tested on Scenario 3856, which was created using test code along these lines, so the change table that's on the server is not valid with the current implementation of TransformGrid. With the new code, it works.
```python
from powersimdata import Scenario
from powersimdata.design.transmission.mwmiles import calculate_mw_miles
scenario = Scenario(3856)
calculate_mw_miles(scenario)
```
15 minutes.

feat: allow scaling of added elements

---

.coveragerc
.github/workflows/test.yml
Pipfile
Pipfile.lock
pytest.ini
requirements.txt
tox.ini

Whenever we run pytest, include a coverage report in the output. This will help with awareness of test coverage, and enable future improvements such as analysis over time and in different areas of the code, or additional ci checks (e.g. we could fail the build if code coverage decreases). 
New packages:
* [coverage](https://coverage.readthedocs.io/en/coverage-5.5/index.html) - the main tool for creating the report
* [pytest-cov](https://pytest-cov.readthedocs.io/en/latest/index.html) - plugin so we can run coverage via pytest
Add the necessary packages to Pipfile and requirements.txt. Consolidated them under the `dev-packages` section and removed version pinning for these only. This makes them available whether running `pytest` directly or via `tox`.
Also added python 3.9 to the test …

Add coverage report to pytest

---

powersimdata/design/transmission/tests/test_upgrade.py
powersimdata/design/transmission/upgrade.py

Allow congested mesh branches to be ranked by mean congestion, rather than only by a quantile value of congestion. Closes #439 (we will create a separate, more detailed issue for the third bullet of #439, which requires more design thought).
Previously, we had a `method` parameter, which only applied to the denominator of the `(congestion metric) / (upgrade cost proxy)` ratio. Now, we have `congestion_metric` and `cost_metric` (replaces `method`). Most of the code changes are simply renaming `method` -> `cost_metric`, and elaborating in the documentation. Within `_identify_mesh_branch_upgrades`, we call `.mean()` rather than `.quantile()` on the congestion data frame as applicable, and we …

feat: allow congested mesh branches to be ranked by mean congestion

---

powersimdata/design/investment/README.md
powersimdata/design/investment/create_mapping_files.py
powersimdata/design/investment/investment_costs.py

Make investment cost independent of grid model (at least from any USA grid model). Closes #430.
Pass a `Grid` object to functions creating the mapping and use the grid model stored in the scenario info when calculating the cost.
No testing
* `write_bus_neem_map` and `write_bus_reeds_map` in `powersimdata.design.investment.create_mapping_files` module
* `calculate_ac_inv_costs`, calculate_dc_inv_costs and calculate_gen_inv_costs in `powersimdata.design.investment.investment_costs` module
* format README
N/A
5min

Make investment modules independent of USA grid models

---

powersimdata/data_access/data_access.py
powersimdata/data_access/profile_helper.py
powersimdata/data_access/tests/test_data_access.py
powersimdata/data_access/tests/test_profile_helper.py
powersimdata/input/input_data.py
powersimdata/input/tests/test_input_data.py
powersimdata/output/output_data.py
powersimdata/scenario/create.py
powersimdata/scenario/delete.py
powersimdata/scenario/execute.py
powersimdata/scenario/move.py
powersimdata/scenario/state.py
powersimdata/utility/server_setup.py

Address several places that were not platform independent.
* Finished splitting up commands between local/ssh and removed the `execute_command` in the local case, as it relied on `/bin/bash`
* Add the `DataAccess.join` attribute according to the subclass, removing hard coded `posixpath.join` in calling code
* Added `get_base_dir` and `match_scenario_files` to encapsulate the logic of creating paths, along with tests for these
* Fix potential issue in `InputData` and `OutputData` which were relying on the values from `server_setup.py`, which had posixpath implicitly hard coded (e.g. `INPUT_DIR = data/input`). We delay the path join by using a tuple instead
* Ran a scenario in docker (using `LocalDataAccess`)
* Created and prepared a scenario on the server and deleted it (using …

Additional support for windows

---

.dockerignore
.gitignore
powersimdata/data_access/context.py
powersimdata/data_access/data_access.py
powersimdata/data_access/execute_list.py
powersimdata/data_access/launcher.py
powersimdata/data_access/scenario_list.py
powersimdata/data_access/tests/test_data_access.py
powersimdata/scenario/analyze.py
powersimdata/scenario/create.py
powersimdata/scenario/delete.py
powersimdata/scenario/execute.py
powersimdata/scenario/move.py
powersimdata/scenario/scenario.py
powersimdata/scenario/state.py
powersimdata/utility/config.py
powersimdata/utility/server_setup.py

Add the remaining code changes so that the framework can be used locally, outside docker, on any os, using a local REISE.jl installation.
* Factor out `launch_scenario` into subclasses for each use case, and similarly for extracting output.
* Add `State.refresh` method so state changes have up to date information without re-initializing the instance
* Split up configuration into classes, making it easy to override values specific to a given environment
* various cleanup
* Ran a simulation end to end on windows. Ran into issues due to using julia 1.6 but upgrading PyCall and CSV packages fixed the issues. 
* Ran simulation on MacOS using julia 1.5 (there are issues with 1.6)
* Ran simulation in plug to verify no regressions
The PR for documentation is …

Support local+native usage

---

powersimdata/scenario/execute.py

Fix a spot which still assumed posix style paths.
Use the join method on the data access instance which is context aware.
We do the same thing elsewhere, so didn't manually check this
3 min

fix: path join for profiles_as

---

powersimdata/input/input_data.py

When performing the `get_bus_demand` function, avoid modifying the bus table of the Grid that is passed as input. This is not a problem when we call `scenario.get_bus_demand()` on a Scenario in Analyze state, since that method passes a fresh copy of the grid so the grid associated with the scenario doesn't change, but it's still an unintuitive behavior in case anyone uses the lower-level function.
Before:
```python
>>> from powersimdata.input.input_data import get_bus_demand
>>> scenario = Scenario(599)
>>> grid = scenario.get_grid()
>>> len(grid.bus.columns)
19
>>> get_bus_demand(scenario.info, grid)
>>> len(grid.bus.columns)
21
```
After:
```python
>>> …
```

fix: create copy of bus table before modifying within get_bus_demand function

---

powersimdata/input/abstract_grid.py
powersimdata/input/change_table.py
powersimdata/input/grid.py
powersimdata/input/input_data.py
powersimdata/input/transform_grid.py
powersimdata/input/transform_profile.py
powersimdata/network/csv_reader.py
powersimdata/output/output_data.py
powersimdata/scenario/create.py
powersimdata/scenario/execute.py
powersimdata/scenario/move.py
powersimdata/scenario/scenario.py
powersimdata/scenario/state.py
powersimdata/tests/mock_grid.py
powersimdata/utility/helpers.py

Address #482 
Define `export_scaled_profile` function which can be called given a profile kind/version, grid, change table, and destination path. We now call this function from `SimulationInput.prepare_profile`, but it could be called independent of a scenario.
Prepared a scenario in a container with a change table and it worked as expected.
10 min

Add function to export profiles

---

powersimdata/data_access/profile_helper.py

I cloned the profiles from the website storage account to our other one, so we need to update the url. Afterwards we can delete the `profiles` container in the `bescienceswebsite` account.
Update the url for the storage account
Ran the profile transformation tests after deleting my local copies
1 min

chore: update blob storage account for profiles

---

powersimdata/input/tests/test_transform_profile.py
powersimdata/scenario/tests/test_create.py
powersimdata/scenario/tests/test_scenario.py

The transform profile tests don't require the server, but if we run them in CI it would require downloading from blob storage each time, which would significantly increase the wait time and bandwidth required. I uploaded some truncated profiles (just using rows for Jan 1) to blob storage, under a new `test_usa_tamu` grid model which we can use in the tests with minimal changes.
Refactor the profile fixtures, point to the new test grid model, add a couple missing pytest markers.
Ran locally and checked the profiles are downloaded to `~/ScenarioData/raw/test_usa_tamu`.
10 min

test: include transform profile tests by default

---

powersimdata/data_access/launcher.py
powersimdata/data_access/tests/test_launcher.py

If no solver is provided we should use the default which is determined in REISE.jl. I think I introduced this bug by adding the validation after having tested the code, and it was not re-tested (d'oh). 
Fix validation and add tests.
New unit tests
3 min

Fix TypeError raised when using using default solver

---

powersimdata/input/export_data.py
powersimdata/input/transform_profile.py
powersimdata/scenario/execute.py

Gather functions that export the grid and the profiles into a single module
* The `powersimdata/input/case_mat` module is renamed to `powersimdata/input/export_data`.
* The `export_scaled_profile` function is moved from the ` powersimdata/input/transform_profile` module to the `powersimdata/input/export_data` module
* The `export_scaled_profile` function is renamed to `export_transformed_profile` to reflect both scaling and adding operations.
N/A
Check that I handled correctly the import statement
N/A
5min

Rename module and move function

---

powersimdata/design/generation/clean_capacity_scaling.py
powersimdata/design/generation/cost_curves.py
powersimdata/design/generation/tests/test_cost_curves.py
powersimdata/design/scenario_info.py
powersimdata/design/tests/test_scenario_info.py
powersimdata/design/transmission/tests/test_upgrade.py
powersimdata/design/transmission/upgrade.py
powersimdata/input/grid.py
powersimdata/tests/mock_grid.py
powersimdata/tests/mock_scenario_info.py

Add the property to grid and mock grid classes as it's commonly used and set at init time.
Simplify the grid constructor by adding `self.grid_model` as an instance variable - no need to try/catch to set `ModelImmutables`. Also set the property in `MockGrid` since it's already available. 
5 min

refactor: set grid_model property on grid

---

Pipfile
Pipfile.lock
powersimdata/input/check.py
powersimdata/input/tests/test_check.py
powersimdata/network/usa_tamu/constants/zones.py
requirements.txt
setup.py

Since we are increasingly looking to constructing Grid objects from datasets besides the `usa_tamu` CSVs, we are increasingly in need of a check that the Grid objects that we are constructing are internally consistent. This PR adds that check (closes #481), and also makes a couple of changes to some of the Western offshore wind buses we added, so that their voltages are consistent with their connected onshore voltages (found by running the tests).
There is one main user-facing `check_grid` function, which activates nine lower-level functions which check the bullet points from #481. Each of these is pretty self-explanatory, with the exception of the connected components check, for which we …

feat: add Grid validation function

---

powersimdata/input/check.py
powersimdata/input/tests/test_check.py

I assume we would want not proceed with the consistency checks unless it's a `Grid` object. Thought I commented on the original PR but evidently it wasn't submitted since only I can see it (something about "pending").  
Update the docstring and raise separate error for type check. Also added try/except around each check.
tox
5 min

More error handling for grid validation

---

powersimdata/design/transmission/substations.py
powersimdata/design/transmission/tests/test_substations.py

Add a feature to calculate the maximum transmission capacity into or out of a substation. This can be helpful e.g. when working to troubleshoot feasibility for a new grid model, when designing a Grid for a new scenario, or when investigating capacity expansion candidates.
In **substations.py**:
- We create a copy of the `grid.branch` data frame which has additional columns for `from_sub` and `to_sub`.
- We group on these `from_sub` and `to_sub` columns, and sum the branch capacities for branches 'from' and 'to' each substation, excluding branches which are 'from' and 'to' the same substation.
- We reindex so that all substation IDs are present in each of the 'from' and 'to' summations.
- Now …

feat: add substation transmission capacity calculation

---

powersimdata/tests/mock_analyze.py

Enable retrieval of pf and dcline_pf from MockAnalyze. This is a follow-up to #501.
2 minutes.

feat: enable retrieval of pf and dcline_pf from MockAnalyze

---

powersimdata/tests/mock_analyze.py
powersimdata/tests/mock_scenario.py

Allow state method passthrough in MockScenario objects. Closes #434.
- in **mock_analyze.py**:
- we add an `exported_methods` class attribute, which will be accessed by the logic in the `MockScenario` class.
- we also add logic to accept and return `storage_e` data.
- in **mock_scenario.py**:
- we copy the passthrough logic from the Scenario object. See #420 for more details.
Manual.
```python
>>> from powersimdata.tests.mock_scenario import MockScenario
>>> demand = Scenario(599).get_demand()
>>> mock_scenario = MockScenario(demand=demand)
>>> mock_scenario.get_demand()
201      202      203  ...      214      215      216
UTC Time …
```

feat: allow state method passthrough in MockScenario objects

---

powersimdata/design/investment/investment_costs.py
powersimdata/input/check.py
powersimdata/input/tests/test_check.py

Currently, the user-facing functions to calculate investment cost for each of {ac branches, dc branches, generation/storage} automatically compare against the base Grid in the repository. This PR adds a new parameter `base_grid` to each of these functions, so that another Grid can be passed instead.
This is useful because the base Grid in the repository does not correspond to any particular point in time, so calculating investment costs between for example a 2021 scenario and a 2030 scenario currently involves calculating the investment costs of each of them compared to the base grid in the repository, and then comparing those differences against each other. If instead the user can say that …

feat: add base_grid input to investment cost calculation functions

---

.github/workflows/coverage.yml
tox.ini

Upload code coverage report to [codecov.io](https://about.codecov.io/) for each merge to develop branch.
Created a separate workflow which is partly duplicated from the test.yml rather than make that more complicated with various conditionals. This keeps the stdout report for per-commit tests but uses the xml report required for uploading to codecov. 
Ran the workflow on this branch, and got a report uploaded, which is available [here](https://codecov.io/gh/Breakthrough-Energy/PowerSimData/commit/434a083c7fcf6e75c64cae84a40850ce8ccede73/). The files and graphs tabs are probably the best place to explore.
10 mins

ci: code coverage reporting

---

.github/workflows/coverage.yml
README.md

Apparently we can't use environment variables in `jobs.<job_id>.name`, so this fixes that. Also added the badge. 
Pushed branch with workflow enabled, to check that the yaml is considered valid.
1 min

ci: fix yaml and add codecov badge

---

powersimdata/design/compare/generation.py
powersimdata/design/compare/helpers.py
powersimdata/design/compare/transmission.py
powersimdata/design/investment/investment_costs.py
powersimdata/input/check.py
powersimdata/input/tests/test_check.py
powersimdata/scenario/check.py
powersimdata/scenario/tests/test_check.py

- Add a new module, `powersimdata.design.compare`, to consolidate code which compares Grid data tables.
- In the process of moving code from PostREISE to PowerSimData, move associated check functions which do not depend on PCM outputs.
- `powersimdata.design.compare` gets comparison logic that had been performed elsewhere in PowerSimData or PostREISE.
- `powersimdata.design.investment` uses the newly consolidated comparison logic.
- `powersimdata.input.check` and `powersimdata.scenario.check` get the Grid and Scenario check functions (with associated tests).
Existing unit tests still pass. The existing comparison logic in PowerSimData was untested, but now has a path to getting tests, since …

refactor: add compare module, move Grid/Scenario check functions from PostREISE to PowerSimData

---

.coveragerc
powersimdata/input/grid.py
powersimdata/network/usa_tamu/model.py
powersimdata/network/usa_tamu/tests/test_model.py

Improve experience of using the grid object by allowing users to provide interconnects as a `set`, and removing duplicates if a `list` is provided. Basically, eliminating the requirement of calling code to do `Grid(list(set(interconnect)))`.
Described above, and some test updates. Also, include tests in code coverage report.
There are good unit tests already, just modified as needed.
```
In [1]: from powersimdata import Grid
In [2]: Grid({'Eastern', 'Texas'})
Reading bus.csv
Reading plant.csv
Reading gencost.csv
Reading branch.csv
Reading dcline.csv
Reading sub.csv
Reading bus2sub.csv
Reading zone.csv
Out[2]: <powersimdata.input.grid.Grid at 0x10f376cd0>
In [3]: Grid(['Texas', 'Texas'])
Reading bus.csv
Reading plant.csv
Reading gencost.csv
Reading branch.csv
Reading dcline.csv
Reading …
```

feat: deduplicate interconnect passed to grid constructor

---

powersimdata/input/check.py
powersimdata/input/helpers.py
powersimdata/input/tests/test_helpers.py

We are moving helper functions from PostREISE to PowerSimData. This is motivated by conversation in https://github.com/Breakthrough-Energy/PostREISE/pull/310; we were discussing the companion PR to #507, which did the same thing for check functions, and we noticed that there is another module that doesn't need to be PostREISE-specific.
Most of the changes are straight copy/paste from `postreise.analyze.helpers`. The exception is in **powersimdata/input/check.py**, in which we move the import of the Grid object into the `_check_grid_type` function to avoid a circular import (since the `powersimdata.input.grid` module imports `powersimdata.input.helpers` which now imports …

refactor: move PostREISE helper functions to PowerSimData

---

powersimdata/scenario/analyze.py

Retrieve onshore and offshore wind profile for a scenario 
Two functions are implemented:
* plant ID are retrieved for each type of turbines 
* wind profile is queried
* an error is raised if no offshore wind profiles id found in the grid
Manual testing for scenario.
Please propose potential test.
Check the `powersimdata.scenario.analyze` module
```
from powersimdata import Scenario
scenario = Scenario(600)
offshore_wind = scenario.get_wind_offshore()
onshore_wind = scenario.get_wind_onshore()
```
10 min

feat: access onshore and offshore wind profiles

---

powersimdata/data_access/sql_store.py
powersimdata/data_access/tests/test_execute_table.py
powersimdata/data_access/tests/test_scenario_table.py

The latest release of pep8-naming now includes N818 which checks the naming of `Exception` subclasses.
Fix the one existing violation .
`tox -e flake8`
1 min

chore: fix N818 warning from pep8-naming

---

powersimdata/input/grid.py
powersimdata/input/tests/test_grid.py

What is the larger goal of this change?
Create a single place where supported models and engines are listed for the `Grid` class. This will allow the download manager project to easily use those supported models and engines as choices for CLI parameters
How is the purpose executed?
Adding class variables to `Grid`
How did you test this change (unit/functional testing, manual testing, etc.)? 
unit tests
N/A
N/A
How long will it take for reviewers and observers to understand this code change?
1 minute

refactor: create class variables for supported models and engines

---

powersimdata/scenario/analyze.py
powersimdata/scenario/create.py
powersimdata/scenario/execute.py
powersimdata/scenario/ready.py
powersimdata/scenario/scenario.py
powersimdata/scenario/state.py

Address #522
Define a new `State` subclass with methods to access transformed profiles, and have `Execute` and `Analyze` inherit from that. 
Checked some of the methods for:
* an existing scenario (analyze state)
* a newly created scenario (create/execute state)
10 min

feat: support getting profiles from execute state

---

powersimdata/data_access/launcher.py

Changes corresponding to https://github.com/Breakthrough-Energy/REISE.jl/pull/146. This exposes the extract-data parameter to a user who is interacting via the scenario object. 
The extract_data parameter is already part of the signature, but needed to be passed to REISE.jl. Also add implementations for `extract_simulation_output` so it can be called when using docker or local installation.
Launched a simulation using docker and natively, with and without extract_data set.
10 min

feat: support passing extract_data for container and local simulations

---

powersimdata/design/generation/clean_capacity_scaling.py
powersimdata/design/investment/investment_costs.py
powersimdata/design/transmission/mwmiles.py
powersimdata/design/transmission/upgrade.py
powersimdata/scenario/create.py
powersimdata/scenario/ready.py

What is the larger goal of this change?
To pay down some tech debt and hopefully make PowerSimData codebase more maintainable
How is the purpose executed?
Removing many similar/copy and pasted calls to initialize the original Grid that a scenario was derived from via information from the scenario object
How did you test this change (unit/functional testing, manual testing, etc.)? 
How long will it take for reviewers and observers to understand this code change?
20 minutes

refactor: add get_base_grid() to states

---

setup.cfg
setup.py

Switch to setup.cfg for package metadata since it's the [recommended](https://packaging.python.org/tutorials/packaging-projects/#configuring-metadata) approach. 
The details are the same as in setup.py, but this also adds some classifiers, project urls, and sets the readme as the `long_description` which will appear on the PyPI page once we publish.
First ran `pip install build`, followed by `python -m build`, which creates a `dist/` folder with `.whl` package file. I installed this in a new environment and checked that I can still import stuff and instantiate a grid (to verify the `package_data` is included).
Also published to the test pypi server, check it out [here](https://test.pypi.org/project/powersimdata/)
5 min

chore: use setup.cfg

---

.github/workflows/release.yml

New workflow to handle building and uploading the package to PyPI whenever we push a new git tag with the specified version scheme. It can also be run manually, so we can test it out on the existing `v0.4.3` release.
Usual workflow stuff. We install the `build` package to create the `dist/` folder which will be uploaded subsequently using the github action provided by pypa.
Tested the release to [TestPyPI](https://test.pypi.org/project/powersimdata/) initially by omitting the tags filter in the `on:` section. Once this is merged I will run the workflow on our latest release, which should also upload to the real PyPI.
10 min

ci: add workflow to build and upload package

---

powersimdata/design/investment/investment_costs.py

Correct a bug introduced in #507.
We had meant to access the `"diff"` column of a DataFrame, but we're instead accessing the `.diff()` method. This fixes that.
Tested manually. Before:
```python
>>> from powersimdata.design.investment.investment_costs import (
...     calculate_ac_inv_costs,
...     calculate_gen_inv_costs,
... )
>>> scenario = Scenario(1705)
>>> calculate_ac_inv_costs(scenario)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Users\DanielOlsen\repos\bes\PowerSimData\powersimdata\design\investment\investment_costs.py", line 76, in calculate_ac_inv_costs
grid_differences.branch = …
```

fix: access column values instead of DataFrame method

---

powersimdata/data_access/profile_helper.py

Simplify the process to use a custom profile - instead of requiring a local version.json, we can just list the existing files.
Extracts the profile version from the filename, for files in the `raw/{grid_model}` folder. We currently assume this folder exists, and the files conform to the current naming convention.
Ran it locally, added a new profile, got expected result:
```
In [17]: ProfileHelper.get_profile_version_local("usa_tamu", "demand")
Out[17]: ['vJan2021', 'vFeb2021']
```
10 min

feat: list available profiles directly

---

powersimdata/input/change_table.py
powersimdata/input/tests/test_change_table.py
powersimdata/input/tests/test_transform_grid.py
powersimdata/input/transform_grid.py

~Partial fulfilment of~ Closes #423. Plants and DC lines can already be _effectively_ removed by scaling them down to zero, this allows branches and buses to be removed as well. If we like the structure of the branch and bus removal, and want to enable full removal of plants, DC lines, storage, etc., then I can amend this PR to include those analogous methods as well.
Within the `ChangeTable` class:
- We add new methods `remove_bus` and `remove_branch`, which check that the elements to be removed are actually in the grid before adding to the change table dictionary. `remove_bus` has a check to ensure that a bus cannot be removed if there's at least one plant with non-zero capacity at it, and …

feat: allow the user to remove lines, buses, plants, and DC lines

---

powersimdata/data_access/data_access.py
powersimdata/input/export_data.py
powersimdata/scenario/execute.py

Update how the inputs to `REISE.jl` get saved to go through exclusively through pyfilesystem instead of saving to local and using pyfilesystem to move to the expected folders for `REISE.jl`
The write function in `data_access` was updated to reflect the fact that the `REISE.jl` inputs don't get saved locally if in the server mode. `export_data` was updated to return the mpc and mpc_storage data instead of saving directly to the local filesystem, though that option was kept in for researchers who may want to use that function to save and investigate the mpc files outside of a scenario workflow (e.g. without having to create a whole scenario and finding it in the `/tmp` folder). Finally, the …

Feat: Update Saving REISE.jl Inputs with Pyfilesystem

---

powersimdata/input/abstract_grid.py
powersimdata/input/grid.py
powersimdata/input/scenario_grid.py
powersimdata/network/hifld/constants/plants.py
powersimdata/network/hifld/constants/storage.py
powersimdata/network/hifld/constants/zones.py
powersimdata/network/hifld/model.py
powersimdata/network/model.py

Allows the user to instantiate HIFLD grid objects by adding the necessary folder structure and sub-modules. Closes #551.
- In `powersimdata.network.hifld.model`: defining an HIFLD class, and populating it with necessary methods. Most of this code is copied directly from `powersimdata.network.usa_tamu.model`
- In `powersimdata.input.grid`: adding `"hifld"` as an allowable model/source input, and instantiating an `HIFLD` object as appropriate.
- In `powersimdata.network.model`: adding `"hifld"` as an acceptable model for instantiating a `ModelImmutables` object.
- Mostly-empty `__init__.py` files as necessary within `powersimdata.network.hifld.constants`. These will be filled in before this PR …

feat: add functionality to load Grid objects with HIFLD grid model

---

powersimdata/network/usa_tamu/constants/zones.py

Add a mapping from state abbreviations to load zone IDs to `zones.py`, where other similar mappings are found.
This mapping essentially inverts the mapping from load zone IDs to state abbreviations, which is also found in `zones.py`.
This new mapping was tested locally and works as expected.
The new mapping can be found in `powersimdata\network\usa_tamu\constants\zones.py`.
This should be very quick. Let me know if you think other reviewers should be added.

feat: add mapping from state abbreviations to load zone IDs

---

powersimdata/data_access/data_access.py
powersimdata/data_access/profile_helper.py
powersimdata/data_access/tests/test_profile_helper.py

Currently the way we do this involves parsing a `version.json` file located in blob storage which must match the versions that are actually available. However to list locally available profiles, we check the files directly, which is more reliable than using the json file. This PR makes it so we use the same code for both local and blob storage, with the only difference being which filesystem is provided. 
See above. It is a refactor to be more consistent and eliminate the need for the `version.json` file.
Ran the `_local` and `_cloud` functions interactively. Added new test for the shared logic (which was already in use, but untested). 
10 min

List profile versions from blob storage

---

powersimdata/input/export_data.py
powersimdata/input/input_data.py
powersimdata/input/transform_profile.py
powersimdata/output/output_data.py
powersimdata/scenario/create.py
powersimdata/scenario/execute.py
powersimdata/scenario/ready.py
powersimdata/scenario/tests/test_create.py
powersimdata/tests/mock_analyze.py

Currently, when we retrieve profiles for a partial-year Scenario, we still return the entire year's profile. This can cause problems, since the time-series results are only defined over the Scenario's time range (see https://github.com/Breakthrough-Energy/PostREISE/issues/327 as an example). This corrects that issue, by slicing both the raw profiles (demand, solar, hydro, wind) and the bus-distributed profiles (via the method/function `get_bus_demand`).
Within `input_data.py`, we decompose the current `get_bus_demand` function into a scenario-info-retrieval step and a decomposition step. The scenario-info-retrieval step now slices the demand profile by time before the decomposition step. The …

fix: when retrieving profiles for partial-year Scenario, slice to Scenario time range

---

setup.cfg

Bump the release number for PowerSimData, in anticipation of a breaking change to the API from https://github.com/Breakthrough-Energy/PowerSimData/pull/581. At the same time, also update the list of supported python versions to reflect that our new requirements are 3.8+.
2 minutes.

chore: bump release number

---

.github/workflows/coverage.yml
.github/workflows/test.yml
Dockerfile
powersimdata/data_access/csv_store.py
powersimdata/data_access/data_access.py
powersimdata/data_access/profile_helper.py
powersimdata/data_access/tests/test_data_access.py
powersimdata/input/input_data.py
powersimdata/output/output_data.py
powersimdata/scenario/analyze.py
powersimdata/scenario/create.py
powersimdata/scenario/delete.py
powersimdata/scenario/execute.py
powersimdata/scenario/tests/test_scenario.py
powersimdata/tests/mock_context.py
tox.ini

Relates to https://github.com/Breakthrough-Energy/PowerSimData/issues/552
Based on the changes introduced in the `data_access_refactor` feature branch, this contains bugfixes and some code cleanup. Additionally it introduces blob storage as a read only source of scenario data, using fs-azureblob to maintain consistency across filesystems. 
* Fix bugs encountered while launching simulations in a container and in preparing one on the server. 
* Remove the `move_to` method which is only being used for the scenario/execute list, and combine with `push` which is what is used for those files
* use `MultiFS` to combine remote filesystems (represented by the `DataAccess.fs` attribute)
* make code coverage report opt in
* new unit test for creating/preparing a scenario using an ephemeral …

Wrap up initial data access refactor

---

.github/workflows/coverage.yml
.github/workflows/test.yml
Dockerfile
powersimdata/data_access/csv_store.py
powersimdata/data_access/data_access.py
powersimdata/data_access/profile_helper.py
powersimdata/data_access/tests/test_data_access.py
powersimdata/input/change_table.py
powersimdata/input/export_data.py
powersimdata/input/input_data.py
powersimdata/output/output_data.py
powersimdata/scenario/analyze.py
powersimdata/scenario/create.py
powersimdata/scenario/delete.py
powersimdata/scenario/execute.py
powersimdata/scenario/tests/test_scenario.py
powersimdata/tests/mock_context.py
tox.ini

Data access refactor and blob storage integration. Someone needs to approve it but I can leave open if folks haven't had a chance to review the recent PR, just lemme know.
This was tested in #570 
Here is the output I get when I change the local directory from `ScenarioData` to an empty directory, then load a scenario from blob storage.
```
In [1]: from powersimdata import Scenario
In [2]: s = Scenario(1270)
Could not connect to ssh server
Initialized remote filesystem with profile_fs,scenario_fs
Transferring ScenarioList.csv.2 from scenario_fs
Transferring ExecuteList.csv.2 from scenario_fs
SCENARIO: Julia | USA2030HVDC_Design3_OB1_Mesh500x38
--> State
analyze
--> Loading grid …
```

Merge data access refactor feature branch 

---

powersimdata/scenario/create.py

Ensure that profiles of appropriate length are being returned in partial-year `Create`-state Scenarios. This got broken during the refactor of #581, and must have been missed while we tested partial-year `Analyze`-state Scenarios.
Now that profile slicing is contained within `TransformProfile`, with a dictionary of Scenario information passed to control the start & end timestamps to slice, we need to make sure that the `_Builder` object passes this information to the `TransformProfile` init.
Manually ran the tests in `powersimdata/scenario/tests/test_create.py` which aren't normally run (since they're marked `integration`.
5 minutes.

fix: pass _Builder start and end date to TransformProfile

---

powersimdata/input/tests/test_transform_profile.py
powersimdata/tests/mock_input_data.py
powersimdata/tests/test_mocks.py

Hi Breakthrough Energy Team! Thank you for your work on this interesting and important project!
This PR is an attempt to fix https://github.com/Breakthrough-Energy/PowerSimData/issues/489.
The  `test_usa_tamu` profiles are no longer needed for `test_transform_profile` and no Internet connection is required to run the tests.
To avoid the Azure blob call, I mocked `InputData` to return random profiles. I just used uniform random data in [0, 1) as suggested [here](https://github.com/Breakthrough-Energy/PowerSimData/pull/485#issuecomment-848331723)
I ran `tox -e pytest-local -- --cov=powersimdata` and `tox -e checkformatting` and both are passing.
To make sure that `test_usa_tamu` was not …

test: Use fake profile data instead of test_usa_tamu

---

powersimdata/tests/mock_input_data.py

With the up-to-date pandas version the eval string in `powersimdata/tests/mock_input_data.py` fails due to a chained call of the `@` accessor. This PR provides a fix for that the error. 
Instead of the `eval` call, use a lambda function for the selection.  
It fixes the tests with the new pandas version.
3 min

mock_input_data: fix eval computation for new pandas version

---

powersimdata/data_access/data_access.py
powersimdata/data_access/profile_helper.py
powersimdata/data_access/tests/test_profile_helper.py
powersimdata/input/tests/test_change_table.py
powersimdata/input/tests/test_transform_profile.py

I wasn't sure how this would work so did some experimenting, made a few tweaks, etc. This makes it so the mocked `DataAccess` instance (or really, any instance) will use the `self.local_fs` attribute to get local profiles, instead of having that be hard coded to use `LOCAL_DIR`. In this case, the local_fs is a `TempFS` so it's completely isolated from existing files. 
See above
tox
5-10 min

Use temp filesystem for profile test

---

powersimdata/input/change_table.py
powersimdata/input/changes/helpers.py
powersimdata/input/changes/storage.py

Move `add_storage_capacity` to its own module. If we like this pattern, I would do the same thing for most of the other change table operations. 
Move the logic to a separate function that takes a change table instance, so the actual method on the `ChangeTable` object becomes a one liner.
tox
5 min

refactor: separate add_storage_capacity

---

powersimdata/data_access/data_access.py
powersimdata/data_access/profile_helper.py
powersimdata/data_access/scenario_list.py
powersimdata/data_access/tests/test_profile_helper.py
powersimdata/input/change_table.py
powersimdata/input/input_data.py
powersimdata/input/tests/test_change_table.py
powersimdata/input/tests/test_transform_profile.py
powersimdata/input/transform_profile.py
powersimdata/output/output_data.py
powersimdata/scenario/analyze.py
powersimdata/scenario/execute.py
powersimdata/tests/mock_input_data.py

The goal of this PR is to allow users to specify demand flexibility profiles and parameters in `PowerSimData`. This PR closes Issue #511.
Demand flexibility profiles and parameters are specified using the change table (via the `add_demand_flexibility` function). Demand flexibility profiles are accessed using the same core functionality as the other profile data. Accessing the demand flexibility profiles does differ slightly in that the profiles are not scaled (as you might see with demand, solar, wind, and hydro) and different area granularity can potentially be included (some combination of zone IDs and bus IDs, consistent with the allowed inputs in `REISE.jl`). This functionality is located …

Specify demand flexibility in the scenario framework

---

powersimdata/input/export_data.py

This PR fixes a typo in `export_data.py`.   
Exporting the ramp limit column for generators to `pypsa`
1 min

export_data: hotfix column name

---

powersimdata/input/input_data.py

If there is a zone with zero demand (i.e. all `"Pd"` values are zero for buses in that zone), `distribute_demand_from_zones_to_buses` will fail, since `pandas.pivot_table` will by default drop some rows/columns and we will end up with a matrix of a different size. This tweak fixes that.
By passing `dropna=False`, we ensure that `pivot_table` returns a matrix of a constant size, no matter whether there are zero-demand zones or not.
Tested manually. Before:
```python
>>> from powersimdata.input.input_data import distribute_demand_from_zones_to_buses
>>> scenario = Scenario()
>>> scenario.set_grid("usa_tamu", "Texas")
>>> scenario.set_base_profile("demand", …
```

fix: make distribute_demand_from_zones_to_buses robust to zero-demand zone

---

powersimdata/input/tests/test_grid.py
powersimdata/input/transform_grid.py

Pandas has been yelling at me whenever I run tests because we are still using `.append` instead of `.concat`. This PR should make pandas happier. 
Change some of the append to concat. It defaults to `sort=False` (see [docs](https://pandas.pydata.org/docs/reference/api/pandas.concat.html)) so I removed that where applicable. 
tox
10 min

Fix some of the pandas deprecation warnings

---

powersimdata/input/change_table.py
powersimdata/input/changes/electrification.py
powersimdata/input/changes/tests/test_add_electrification.py
powersimdata/scenario/scenario.py

Define/implement new schema for electrification profiles and scaling by grid/zone. 
Define one new function `add_electrification` which can specify profiles and scaling for supported types: currently these are building and transportation. If specifying scaling factors by zone, the zone name is checked against the current grid object. There isn't yet validation for the profile name/version, but I'll add that if the general approach looks good. 
Depending on expected usage patterns, the schema could also be "inverted" by mapping profiles to zones and scaling factors, but I think either way has trade offs in how easy it is to specify the change table and how much code is required to aggregate the profiles during the preparation phase. 
New unit tests.
The tests are the best usage example. …

Add electrification profiles to change table

---

powersimdata/scenario/create.py

Fix a bug when creating scenarios, `start_date` and `end_date` can be set at the boundaries of the time range, i.e. `start_date` can't be `2016-12-31 23:00:00` and `end_date` can't be `2016-01-01 00:00:00`. This shouldn't be the case given our time range is inclusive, which will prevent users from running 1h scenarios for the first or the last hour of the year.
A hot fix on the input checks.
An integration test of running a 1h USA scenario is successfully conducted.
`powersimdata/scenario/create.py`
Before it gives value error: 
Now it runs successfully
2 min

fix: make start_date and end_date applicable to boundaries

---

powersimdata/input/change_table.py
powersimdata/input/changes/__init__.py
powersimdata/input/changes/demand_flex.py
powersimdata/input/changes/storage.py

Continue factoring out change table methods. 
Move add_demand_flexibility to a separate module. Also combined imports into the `__init__.py`, which is not really a thing we do elsewhere, but seemed ok (can't think of any issues, but if there are we can skip that). 
tox
5 min

refactor: move add_demand_flexibility to own module

---

powersimdata/input/helpers.py

Fix bug introduced in #609.
We change `list(set_a) & set_b` to `list(set_a & set_b)`
Tested manually. Before: PostREISE tests which use `decompose_plant_data_frame_into_resources` fail. After: they don't.
2 minutes.

fix: convert set to list after intersection operation

---

powersimdata/data_access/data_access.py
powersimdata/data_access/fs_helper.py
powersimdata/input/electrified_demand_input.py
powersimdata/input/input_base.py
powersimdata/input/profile_input.py
powersimdata/input/tests/test_profile_input.py

Enable loading electrification profiles from blob storage or local disk, and listing the available versions. This is kind of a draft since we haven't actually uploaded the profiles or determined if this is the best way to organize them, but it is easy to change that later if we want.
New `InputBase` subclass to reuse some of the functionality (e.g. caching) but rather than overloading the `scenario_info` parameter in `get_data` I just created a separate method with the relevant parameters. Also, to reuse the chunk of code in `DataAccess` that combines blob and local profiles, the logic is factored out into a function specific to each module and passed as a callback that takes just the filesystem object as an argument. 
New unit test.
15 min

Add subclass to get electrification profiles and versions

---

powersimdata/scenario/analyze.py

Fix a bug, where calling `Scenario.get_load_shed()` on a Scenario without any load shed throws an Exception.
```python
>>> Scenario(3497).get_load_shed()
[...truncated...]
No infeasibilities, constructing DataFrame
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Users\DanielOlsen\repos\bes\PowerSimData\powersimdata\scenario\analyze.py", line 199, in get_load_shed
filepath = os.path.join(server_setup.LOCAL_DIR, output_dir, filename)
File "C:\Python39\lib\ntpath.py", line 117, in join
genericpath._check_arg_types('join', path, *paths)
File "C:\Python39\lib\genericpath.py", line 152, in _check_arg_types
raise …
```

fix: avoid Exception when calling get_load_shed on a Scenario without load shed

---

powersimdata/design/generation/clean_capacity_scaling.py
powersimdata/design/generation/cost_curves.py
powersimdata/design/transmission/upgrade.py
powersimdata/input/helpers.py

Use the `model_immutables` attribute of the `Grid` object to invoke `area_to_loadzone`. This is a step towards a larger refactoring for non USA grid models. 
* Remove import statement
* Use `grid.model_immutables.area_to_loadzone(area, area_type=area_type)` in place of `area_to_loadzone(grid.mode, area, area_type=area_type)`
Run existing tests
Several modules are impacted but changes are minor. 
How the code can be used and/or images of any graphs, tables or other visuals (not always applicable). 
5min

Change access to area_to_loadzone function

---

powersimdata/input/tests/test_transform_demand.py
powersimdata/input/transform_demand.py
powersimdata/input/transform_profile.py

Apply the change table scaling for electrification profiles, and combine that with scaled demand profile when preparing a scenario.
Add new class `TransformDemand`, where we use the `.value()` method to get the demand profile for a given grid, and given class of electrification. In `TransformProfile`, we add that to the base demand, for each kind of electrification specified in the change table.
Most of the logic in `TransformDemand` is to kind of invert the change table mapping, which makes the transformation logic simpler, as we just fetch one profile at a time, scale it, and sum the results.  
Haven't done integration tests yet, but we have a new unit test that combines grid and zone …

Aggregate demand profiles during scenario preparation

---

powersimdata/data_access/csv_store.py
powersimdata/data_access/data_access.py
powersimdata/scenario/execute.py

Fix the issue where a user won't get a scenario list with existing local scenarios if not connected to the server. 
Best effort to download and use any possible copies of scenario or execute list csv. The local copies are updated with the latest version if possible (always for blob storage, and server copy if connected). Then the results are combined, since we might as well handle a case where the local copy hasn't been updated since the last time we add scenarios to blob storage. 
Unrelated: noticed that the `.copy()` data access method is only used in one place, so removed it from the interface. 
Manual testing: load `Scenario(824)` which is not in blob storage, but is in my local ScenarioList.csv. If not connected to the server, it will load as much as possible but fails since I don't …

Combine scenario list from different sources

---

powersimdata/input/abstract_grid.py
powersimdata/input/grid.py
powersimdata/input/scenario_grid.py
powersimdata/network/constants/region/usa.py
powersimdata/network/hifld/model.py
powersimdata/network/tests/test_helpers.py
powersimdata/network/usa_tamu/model.py
powersimdata/scenario/create.py

Set the `grid_model` and `model_immutables` attributes of the `Grid` class within their respective model. The model immutables  will no longer be a static object for Europe. The loadzone are the buses and it is necessary to instantiate a PyPSA `Network` object to access the bus table. Moreover the number of loadzone will depend on the spatial reduction. 
The `model_immtables` attributes is now set in the  `TAMU`, `HIFLD`, `FromREISE` and `FromREISEjl`. This will set the ground for Europe. To avoid to build the network if we just want to access the model immutables, a `build` method is added to the `TAMU` and `HIFLD` class. One change too is that the `model_immutables` of a `Grid` object now …

Refactor Grid object

---

powersimdata/input/export_data.py
powersimdata/input/grid.py
powersimdata/input/import_data.py
powersimdata/input/tests/test_import_from_pypsa.py
powersimdata/scenario/create.py
powersimdata/scenario/scenario.py

Allow to create Grid or Scenario objects from PyPSA networks. The PR also introduces some changes outside of the newly introduced `import_data` module. This are: 
*  The `Grid` class has a new attribute `SUPPORTED_IMPORTS` used in the `Grid` initialization process. The check in the beginning of the initialization that the `source` argument is in `SUPPORTED_MODELS` was extended to a check that `source` is in `SUPPORTED_MODELS` or in `SUPPORTED_IMPORTS`. Further, when `data_loc` of the imported data is in `SUPPORTED_IMPORTS`, immutables are not loaded into the Grid. This means, as soon as `data_loc` is in the `SUPPORTED_IMPORTS` set, the model is not required to be in `SUPPORTED_MODELS`. The `SUPPORTED_IMPORTS` set is for now only containing "pypsa". 
* The `Grid` initialization skips …

Pypsa importer for scenario objects

---

powersimdata/export/export_scenario_inputs.py
powersimdata/export/export_to_pypsa.py
powersimdata/export/tests/test_export_to_pypsa.py
powersimdata/scenario/execute.py

Relocate functions taking care of exporting data to files or other objects  
New modules are created:
* `powersimdata.export.export_scenario_inputs` enclosing the functions that create the case mat file and the CSVs of the transformed profiles
* `powersimdata.export.export_to_pypsa` enclosing the function that translate a `Grid` or a `Scenario` object to PyPSA `Network` object
* Removed the logic around the import of the `pypsa` package (check for it in the test though to avoid failure) since the `export_to_pypsa` function is now in its own module, an `ImportError` won't affect  import of any other function anymore. 
Run existing unit tests
In the new **PowerSimData/powersimdata/export/** …

Relocate functions exporting data

---

powersimdata/input/grid.py

Remove `hifld` from list of supported models since we will likely merge the `hifld` branch into `develop` before we have the HIFLD grid model ready.
If a user tries to instantiate the `Grid` class with the source parameter set to `hifld` a `ValueError` will be raised. Also, the `set_grid` method of the `Create` class will throw the same error. 
```
>>> from powersimdata import Grid
>>> g = Grid("ERCOT", source="hifld")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/brdo/CEM/PowerSimData/powersimdata/input/grid.py", line 35, in __init__
raise ValueError(
ValueError: Source must be one of usa_tamu or the path to a .mat file that represents a grid 
```
The …

chore: remove hifld from list of supported model

---

powersimdata/design/investment/investment_costs.py

I got an error using `calculate_dcline_difference` since it checks that the parameters are `Grid` instances. We use other grid attributes within that function, so we simply pass the grid object (instead of removing the type check). 
Pass full grid object.
Manually in a container. I ended up with a different error due to having an empty `grid.dcline` but that is not surprising. 
2 min

fix: pass grid instead of grid.dcline

---

powersimdata/export/export_to_pypsa.py

Add missing rename value when converting a `Grid` object to a `Network` object. I forgot to include it when I updated the `export_to_pypsa` function from changes made in #608. As a result, the `c1` column will not be renamed to `marginal cost` as expected by PyPSA
N/A
I found the bug in the `ben/import` branch when trying to convert back to a `Grid` object a `Network` object previously created from a `Grid` object.
You can compare what is done in #608 (see [here](https://github.com/Breakthrough-Energy/PowerSimData/blob/fab8f67d3c02b797b778bcc0a8b4c7603d0e2767/powersimdata/input/export_data.py#L80))
N/A
2min

Fix PyPSA exporter

---

powersimdata/input/exporter/export_to_pypsa.py
powersimdata/network/constants/plants.py

Fix the unit conversion when exporting co2 emission rates to pypsa networks. Pypsa specifies co2 emissions in tonnes per MWh_thermal, powersimdata in kg per MWh_electric. A new dictionary was added to `plants.py` specifying the type dependent efficiencies. These are necessary for the conversion and are taken from the Danish Energy Agency.   
No tests added
2 min

fix: add conversion factor for co2 emissions when exporting to pypsa

---

powersimdata/network/europe_tub/model.py

Use PyPSA-Eur extra components files. These ones include, among other things, `stores`
N/A
Before:
```
(PowerSimData) [~/CEM/PowerSimData] (ben/import) brdo$ python
Python 3.9.11 (main, May  4 2022, 12:39:41) 
[Clang 12.0.0 (clang-1200.0.26.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from powersimdata.network.europe_tub.model import TUB
>>> tub = TUB("Europe", reduction=1024)
Title: PyPSA-Eur: An Open Optimisation Model of the European Transmission System (Dataset)
Keywords: power system model, capacity expansion model, energy system model, electricity system model, python
Publication date: 2021-09-22
DOI: 10.5281/zenodo.5521712
Total size: 1767.1 …
```

Update link to PyPSA-Eur files

---

powersimdata/output/output_data.py
powersimdata/scenario/analyze.py

Fix bugs in `Analyze` class and update docstring of the `OutputData` class
Unindent the `get_load_shift_up` and `get_load_shift_dn`methods that were declared within the `get_load_shed` methods
Changes touch the `Analyze` class. A docstring is updated in the `OutputData` class
N/A
2 min

Fix bugs in the Analyze class affecting demand flexibility

---

powersimdata/input/abstract_grid.py
powersimdata/scenario/demo/scenario_and_grid_cheatsheet.ipynb

Change a key word in storage template to make it consistent with elsewhere, replace "energy_price" by "energy_value". 
Close #662 
Replace "energy_price" by "energy_value" in `storage_template` and rerun `scenario_and_grid_cheatsheet.ipynb` to reflect the change with the latest UI.
The demo notebook prints the updated key word.
`powersimdata/input/abstract_grid.py`
`powersimdata/scenario/demo/scenario_and_grid_cheatsheet.ipynb`
See `scenario_and_grid_cheatsheet.ipynb`
5 min

fix: replace "energy_price" by "energy_value" in storage template

---

powersimdata/tests/mock_analyze.py
powersimdata/tests/test_mocks.py

Add method returning profiles for a mock scenario
Add the `get_profile` method to the `MockAnalyze` class. Demand, hydro, solar and wind profiles of a `MockScenario` object can be obtained this way.
New unit test
In the `powersimdata.tests.mock_analyze` and `powersimdata.tests.test_mocks` modules
N/A
5min

Add method to mock scenario

---

powersimdata/input/helpers.py

Fix some deprecation warnings. Those are raised in PostREISE.
Convert sets to lists when querying data frame
Existing unit tests. I checked the warnings were not raised anymore in PostREISE:
Before
```
[~/CEM/PostREISE] (develop) brdo$ tox -r
pytest recreate: /Users/brdo/CEM/PostREISE/.tox/pytest
pytest installdeps: pipenv
pytest installed: certifi==2022.6.15,distlib==0.3.5,filelock==3.8.0,pipenv==2022.8.17,platformdirs==2.5.2,virtualenv==20.16.3,virtualenv-clone==0.5.7
pytest run-test-pre: PYTHONHASHSEED='3396604905'
pytest run-test: commands[0] | pipenv sync --dev
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, …
```

Handle deprecation warnings

---

powersimdata/input/change_table.py
powersimdata/input/changes/demand_flex.py
powersimdata/input/check.py
powersimdata/input/tests/test_change_table.py
powersimdata/input/tests/test_check.py
powersimdata/input/tests/test_input_data.py
powersimdata/scenario/analyze.py
powersimdata/scenario/create.py
powersimdata/tests/mock_context.py

Reduce test duration by reusing objects that don't really need to be recreated. 
* Create fewer instances of `OutputData`, `InputData`, and `ProfileInput`.
* Use texas grid for demand flexibility test instead of usa
* use `None` as default argument
* skip test that downloads from zenodo 
Running the tests locally shows a small but not totally insignificant reduction in test duration. 
2 min

Perf improvements for tests and minor fixes

---

powersimdata/input/exporter/export_to_pypsa.py
requirements.txt

Generating docs for a given module requires importing it, so we need to install any packages it uses at the top level. E.g. the [docs for europe_tub](https://breakthrough-energy.github.io/docs/powersimdata.network.europe_tub.html#module-powersimdata.network.europe_tub) is missing for this reason.
Add packages to requirements.txt and fix one place where the newline causes docs to not render properly ([this one](https://breakthrough-energy.github.io/docs/powersimdata.input.exporter.html#powersimdata.input.exporter.export_to_pypsa.export_to_pypsa))
Built the docs locally.
1 min

docs: add packages to requirements.txt, to fix import errors in sphinx

---

powersimdata/network/constants/resource.py

Use `PHS` instead of `phs` as resource name. 
No code
The modification takes place in the attributes of the `EUResource` class in the `powersimdata.network.constants.resource` module.
PyPSA-Eur uses `PHS` (upper case) for pumped hydro storage as illustrated below:
```
>>> from powersimdata.network.europe_tub.model import TUB
>>> tub = TUB("Europe", reduction=1024)
Title: PyPSA-Eur: An Open Optimisation Model of the European Transmission System (Dataset)
Keywords: power system model, capacity expansion model, energy system model, electricity system model, python
Publication date: 2022-09-10
DOI: 10.5281/zenodo.6913032
Total size: 2075.6 MB
Link: …
```

Fix resource name resource name

---

powersimdata/input/expansion_candidates.py
powersimdata/input/tests/test_expansion_candidates.py

Define a new data structure for expansion candidates and some preliminary validation based on the current grid. The schema is the same as in https://github.com/Breakthrough-Energy/PowerSimData/pull/641 but I refactored it a bit.
Add the new class, which can have candidates for branches, plants, and storage. Each one has a set of allowed columns and required columns. When assigning a given type of candidate, there are some basic checks - e.g. buses are in the grid. I imagine more checks could be done in subsequent PRs. 
We've discussed expanding the costs over multiple years to account for inflation - this isn't accounted for yet, and I suspect it might be done during the preparation phase, after a user has defined the investment years/time span. 
In general there is probably a lot from …

add data structure for expansion candidates

---

powersimdata/input/const/grid_const.py
powersimdata/input/const/pypsa_const.py
powersimdata/input/converter/pypsa_to_grid.py
powersimdata/input/exporter/export_to_pypsa.py

This fixes the conversion for the roundtrip PyPSA -> PSD -> PyPSA. 
Test it with 
```python
from powersimdata.input.converter.pypsa_to_grid import FromPyPSA
from powersimdata.network.europe_tub.model import TUB
from powersimdata.input.exporter.export_to_pypsa import export_to_pypsa
from pandas.testing import assert_frame_equal
tub = TUB("Europe", reduction=1024)
tub.build()
g = FromPyPSA(tub.network)
n = export_to_pypsa(g)
for c in n.iterate_components():
if c.name in ['Carrier']:
continue
orig = tub.df(c.name)
conv = c.df
assert_frame_equal(conv[orig.columns].head(), orig.head())
```
Missing points:
* The distinction between Stores and StorageUnits is not yet completed
* The carrier roundtrip conversion is not complete as it depends on internal static data on PSD side.

Fix roundtrip PyPSA -> PSD -> PyPSA

---

.dockerignore

Reduce docker build time and image size by excluding cached network objects.
See above. Note this is probably only relevant for local builds. Also, once we standardize on downloading grid data from zenodo, this could be generalized to `powersimdata/network/**/data`.
Observed the reduction in build time and image size.
10 sec

chore: add data folder to dockerignore

---

powersimdata/network/constants/carrier/resource.py

Update constants of grid models. To be able to reproduce the previous scenarios with the `usa_tamu` model, the default value for `pmin_as_share_of_pmax` is set to 1 (i.e. `Pmin` is equal to the power output given in the profile each hour) for hydro. As discussed in other channels, the value for `ror` is set to 0 (fully curtailable) in the `europe_tub` model. Finally, PHS is added to the list of clean resources.
Change some constants value and update a dictionary
Current unit tests
It is pretty minimal. The changes has been discussed during meetings and chat conversations.
N/A
5min

Change constants of grid models 

---

powersimdata/network/constants/carrier/resource.py

Combine `hydro` and `PHS` into `inflow` for the `europe_tub` grid model following discussion [here](https://github.com/Breakthrough-Energy/PowerSimData/pull/691#issuecomment-1285989932).
Only dictionaries grouping generators are modified.
Remove `hydro` and `PHS` in the various dictionaries in the `powersimdata.network.constants.carrier.resources` module and add `inflow`.
NA
2min

Create a single inflow carrier in model immutables for hydro and PHS

---

.gitignore
Pipfile
powersimdata/network/europe_tub/model.py
powersimdata/network/zenodo.py
requirements.txt

Build the `Zenodo` class around the [Zenodo Rest API](https://developers.zenodo.org/) to efficiently handle data coming from different record. Partially addresses #687.
* downloads data of a user specified record
* calculate checksum of previously downloaded data and erase then download new copy if necessary
* print information about record (title, version, etc)
Manual testing.
* write `Zenodo` class in `powersimdata.network.zenodo` module
* update the `TUB` class located in the `powersimdata.network.europe_tub.model` module
* remove obsolete `zenodo_get` package from **Pipfile** and **requirements.txt**
```
>>> from powersimdata.network.zenodo import Zenodo
>>> z = Zenodo("3601881")
Title: …
```

Create a Zenodo download manager

---

Pipfile.lock
powersimdata/design/investment/investment_costs.py
powersimdata/tests/mock_profile_input.py

Update **Pipfile.lock** file and fix error and warnings raised by new version of `pandas`
N/A
* handle a `FutureWarning` raised by `pandas` (FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function) in the `investment_costs` module
* Use `list` in place of `set` in the `mock_profile_input` module. That was generating several an error in several tests.
N/A
5min

Update pipenv lock file

---

powersimdata/tests/mock_profile_input.py

Generalize generator type in the `MockProfileInput` class by using information from the `model_immutables` attribute of the `Grid` object
Replace hard coded generator type with a dictionary grouping profile to generator type that is available through an attribute of a `Grid` object for all grid model
Existing unit tests. To get the tests in the `powersimdata.tests.test_mock` module pass, I had to sort the keys in the `grid.model_immutables.plants["group_profile_resources"]` dictionary to mirror what was hard coded before to get the random numbers in `_random` assigned to the same profile. 
The `powersimdata.tests.mock_profile_input` module
N/A
5min

Generalize generator type in MockProfileInput

---

powersimdata/input/check.py

Generalize area type type in check function so we can check for the european model that a given list of countries are in the grid.
Replace hard coded `state` by the `grid.model_immutables.zones["diivision"]` string that gives the division type (state or country so far) for a grid model
Look at the `_check_areas_are_in_grid_and_format` functions. Other modifications are docstring improvements
N/A
2min

Generalize area type in check function

---

powersimdata/input/converter/pypsa_to_profiles.py
powersimdata/input/converter/tests/test_pypsa_to_profiles.py

Extract generator and demand profiles from a PyPSA `Network` object
Loop through the `Generator` and `StorageUnit` components of a `Network` object and build user specified profiles through a dictionary mapping profile type (hydro, solar, wind) to carriers (onwind, solar, ror, etc). Inflow profiles are normalized such that the maximum inflow is 1
New unit tests
The `get_pypsa_gen_profile` function
```
>>> from powersimdata.input.converter.pypsa_to_profiles import get_pypsa_gen_profile
>>> from powersimdata.network.europe_tub.model import TUB
>>> profile2carrier = {'hydro': {'hydro', 'ror', 'PHS'}, 'solar': {'solar'}, 'wind': {'onwind', 'offwind-ac', 'offwind-dc'}}
>>> tub = TUB("Europe", …
```

Extract profiles from PyPSA's Network objects 

---

powersimdata/design/generation/cost_curves.py
powersimdata/design/generation/tests/test_cost_curves.py
powersimdata/input/configure.py
powersimdata/input/input_data.py
powersimdata/input/tests/test_configure.py
powersimdata/input/tests/test_input_data.py
powersimdata/scenario/analyze.py
powersimdata/scenario/execute.py

To facilitate using a grid.pkl and remove the need for mapping between a case.mat/grid.mat/etc, we move grid modifications previously done in REISE.jl to the scenario preparation process. 
This PR should be merged at the same time as https://github.com/Breakthrough-Energy/REISE.jl/pull/187, after which we should update the existing grid.mat files. I believe we also need to update the ramp30 values in plant.csv as discussed in this issue https://github.com/Breakthrough-Energy/PowerSimData/issues/680 and release a new dataset on zenodo.
Scale plant Pmin values and linearize cost curves the same way we were doing in REISE.jl - after we apply the change table, and just before we upload the grid.pkl to the server (or, container, or wherever). I also ported the linearize_gencost tests from …

Port linearize_gencost and pmin modifications from REISE.jl

---

Pipfile
Pipfile.lock

Move `pypsa` to the standard packages section so it is available by default.
Regenerate the lock file. As usual there are some minor updates of other packages, according to the version spec.
tox
2 min

chore: move pypsa from dev-packages

---

powersimdata/input/transform_grid.py

Fix error when we add buses, e.g. via the demo_western.py script in plug. Without the index name, the grid.pkl used in call.py cannot be exported to csv. This should address the issue from the community slack.
Add the index name for bus data frame. We already had this for the other ones but since it was tested with the demo_texas script, which doesn't transform buses, the error didn't occur.
Ran a simulation using the western demo and didn't have the error anymore.
2 min

fix: set bus_id index name

---

setup.cfg

Currently pypsa isn't installed after doing `pip install powersimdata` or `pip install postreise` which causes import errors.
Add pypsa to list of packages installed via pip.
n/a
1 min

chore: add pypsa to install_requires

---

powersimdata/data_access/tests/test_scenario_csv.py
powersimdata/input/converter/pypsa_to_grid.py
powersimdata/input/grid.py
powersimdata/network/europe_tub/model.py
powersimdata/network/zenodo.py
powersimdata/scenario/create.py
powersimdata/utility/templates/ScenarioList.csv

Add workflow to run scenario in PyPSA-Eur grid model.
* Modify schema of ScenarioList. A new `grid_model_version` field is added that will track the version of the files downloaded from Zenodo. Only applies to `europe_tub` grid model. New scenario for `usa_tamu` will have an empty entry. 
* Instantiate a European grid through `set_grid` (UI) as shown in the example below and set the version of the profiles based on the version of the network and the reduction parameter 
Most of the code is in `powersimdata.scenario.create`. Some tweaks in other modules where necessary to be able to access the network version and correctly set the `data_loc` attribute of the `Grid` object …

Enable workflow for europe_tub grid model

---

powersimdata/input/const/grid_const.py
powersimdata/input/const/pypsa_const.py

Add the EIA ID LSE of each bus in the system as an additional column, to be used later to match with LSE-based demand flexibility and use for simulation in REISE.jl [(link).](https://github.com/Breakthrough-Energy/REISE.jl/pull/178) The EIA IDs are identified using an offline process that will be a separate PR in PreREISE.
added a new column in network/usa_tamu/bus.csv
only change is in network/usa_tamu/bus.csv
5 min

feat: EIA ID of buses in the synthetic grid
