powersimdata/input/input_data.py

Cache input data read from disk, to speed up cases where we load the same profile several times.
Look at the second commit only (@rouille will handle cherry-picking and rebasing as necessary). Following the pattern in grid.py, when we are going to load data from disk, we first check the cache. If we don't find it there, we proceed as normal, and cache it after we successfully load.
Unit tests pass. @rouille will test to see if it speeds up the tests in https://github.com/Breakthrough-Energy/PowerSimData/pull/382.
10 minutes. The code is simple, but let's think through if there may be any unintended consequences.

refactor: use profile cache for input data

---

README.md

Provide a link for user to install the whole model as well as the contribution guide.
README first paragraph
5min

docs: add link to installation and contribution guide

---

Pipfile
Pipfile.lock
requirements.txt

Use the latest versions and make the spec more flexible, so we automatically update minor and patch versions.
Updated Pipfile and requirements.txt, and regenerated Pipfile.lock.
automated tests
5 min

Upgrade numpy/scipy

---

.github/workflows/docs-trigger.yml

Use the action defined in our actions [repo](https://github.com/Breakthrough-Energy/actions).
The same thing it was before
Will be tested by merging
3 min

ci: use pre defined action to trigger workflow

---

powersimdata/data_access/scenario_list.py
powersimdata/data_access/sql/schema.sql
powersimdata/data_access/tests/test_scenario_csv.py
powersimdata/data_access/tests/test_scenario_table.py
powersimdata/utility/templates/ScenarioList.csv

Update the schema of the scenario list (csv and sql)
Add an extra field `grid_model`
How did you test this change (unit/functional testing, manual testing, etc.)? 
Look for an extra field named `grid_model` in the scenario list template.
2min

Modify schema of scenario list

---

README.md

Update code snippet following the refactoring of the `Create` class
the code snippet has been tested in the containerized framework.
Section 2.B of the README
2min

Update code snippet of README

---

powersimdata/input/case_mat.py

Fix copy/paste typo in docstring. Pointed out by @LFPower: see https://github.com/Breakthrough-Energy/PowerSimData/commit/d7c6f3343a6b352380322ceea4c4e7a7a8e3c2e5#r48957181.
10 seconds.

doc: fix docstring

---

powersimdata/input/grid.py

Improve docstring of `Grid` class
No code
No test
Description of the `interconnect` parameter of the constructor
None
1 min

docs: improve docstring of Grid class

---

setup.py

Bump version number in **setup.py**, as the final step before merging https://github.com/Breakthrough-Energy/PowerSimData/pull/468.
10 seconds.

chore: bump version number to v0.4.1

---

powersimdata/data_access/profile_helper.py
powersimdata/input/input_data.py

- Correct docstrings for `scenario_info` parameters: they're not instances of a `ScenarioInfo` object.
- Add periods to all other docstrings in the affected files.
No code.
2 minutes.

doc: update docstrings for input_data and profile_helper

---

setup.py

For the purpose of #498, we will want to bump the version number.
5 seconds.

chore: bump version number to v0.4.2

---

powersimdata/tests/mock_analyze.py

Add pf input to MockAnalyze.
Exactly the same as all the other inputs
30 seconds to ponder why we didn't do this before.

chore: add pf input to MockAnalyze

---

powersimdata/input/export_data.py

Add a missing parameter to a function docstring.
No code.
2 minutes.

doc: add docstring for kind param in export_transformed_profile

---

setup.py

Companion to #514.
30 seconds.

chore: bump version number to v0.4.3

---

powersimdata/design/compare/transmission.py
powersimdata/design/investment/investment_costs.py

Rename a function so that its name follows the same convention than the other one in the module
No code
N/A
Function declaration 
N/A
1min

chore: rename function

---

docs/grid.rst
docs/scenario.rst

This is a follow-up to #420, updating the parts of the docs with the remaining old syntax.
No code.
5 minutes.

doc: update Scenario documentation to reflect simpler syntax

---

powersimdata/data_access/launcher.py
powersimdata/scenario/execute.py
powersimdata/scenario/state.py

Fix typos in docstrings.
2 minutes.

doc: fix typos in docstrings

---

powersimdata/data_access/launcher.py

This is a companion to https://github.com/Breakthrough-Energy/REISE.jl/pull/148, and enables this new solver interface to be selected from within PowerSimData.
Add an entry to a tuple.
Not tested.
1 minute.

chore: add clp to list of allowed sovlers

---

README.md

Update README to reflect package availability on PyPi
N/A
N/A
* new badge
* reorganize `Where to get it` section
[here](https://github.com/Breakthrough-Energy/PowerSimData/blob/ben/readme/README.md)
2min

docs: update README to signal package availability on PyPi

---

powersimdata/data_access/data_access.py

Simplify existence check based on this [discussion](https://github.com/Breakthrough-Energy/PowerSimData/pull/459#discussion_r732236686). Standardize behavior of `get_profile_version` based on discussion with Anna.
See above
Manually tested each of the 4 branches in `_check_file_exists`. 
5 min

refactor: simplify _check_file_exists and get_profile_version

---

setup.cfg

chore: bump version number to v0.4.5

---

powersimdata/input/check.py

Add a check for branches which connect to the same bus.
Simple pandas comparisons, extending the existing `check_grid` function.
Tested manually using the grid generated by the current `hifld` branch of PreREISE: the test fails. When we use the data generated by the updated branch from https://github.com/Breakthrough-Energy/PreREISE/pull/263, the test passes.
5 minutes.

test: add grid check for loop branches

---

powersimdata/design/generation/cost_curves.py

Purely style.
No changes.
Existing style checks with new version of `black` (22.1.0) will pass.
1 minute.

style: update black formatting for exponentiation.

---

Pipfile
Pipfile.lock
powersimdata/design/tests/test_scenario_info.py
powersimdata/input/export_data.py
powersimdata/input/tests/test_export_to_pypsa.py

This PR introduces a new function `export_to_pypsa` in the module `powersimdata.input.export_data`. It may take a `Grid` object or a `Scenario` object. 
As I see it, the only information which is not translated is the `storages`. As discussed the `storages` structure in the `Grid` object will likely be changed in near*ish* future. A warning is given when the `Grid` object contains storages. 
Here a short example
```python 
from powersimdata.input.export_data import export_to_pypsa
from powersimdata import Grid
interconnect='USA'
g = Grid("USA")
n = export_to_pypsa(g)
```
The function has a flag `preserve_all_columns` which, when set to True, will store all columns given by the `Grid` object …

Enable Export from Scenario/Grid to pypsa.Network

---

powersimdata/input/change_table.py
powersimdata/input/changes/storage.py
powersimdata/input/export_data.py
powersimdata/input/tests/test_export_to_pypsa.py

Fix docstrings
N/A
N/A
Several files are concerned. The errors were raised when running `sphinx`
N/A
2min

Fix docstrings

---

powersimdata/input/change_table.py
powersimdata/input/changes/bus.py
powersimdata/input/changes/plant.py

Split up change table methods into separate modules/functions. 
Add modules for `plant` and `bus` and move (some) associated methods there. Docstrings link to the function implementation as discussed in #596.
tox
10 min

Factor out change table methods

---

tox.ini

Clean up ***tox.ini*** file
N/A
Run successfully `tox`
Remove unnecessary environment variables
How the code can be used and/or images of any graphs, tables or other visuals (not always applicable). 
2 min

chore: clean up tox file

---

setup.cfg

Bump version for new release
n/a
Ran a simulation in docker using the develop branch 
A moment

chore: bump version number to v0.5.1

---

setup.cfg

After merging #619, bump the version number again so that PostREISE will build off of a non-bugged version of PowerSimData.
30 seconds.

chore: bump version number

---

powersimdata/input/helpers.py
setup.cfg

Merge develop to master for v0.5.2
Fixes, etc:
- #619
- #620
Full changelog https://github.com/Breakthrough-Energy/PowerSimData/compare/v0.5.0..v0.5.1

merge develop into master for v0.5.2 release

---

powersimdata/input/abstract_grid.py
powersimdata/network/hifld/model.py
powersimdata/network/usa_tamu/model.py

Create an abstract grid class for grid models that enclosed in CSVs files. In the future, some grid models will be stored in other forms so it is important to make the distinction
Create a new class dedicated to the reading of CSV grid models (`AbstractGridCSV`) that inherits from a higher level `AbstractGrid` class
Run `tox` successfully
The `powersimdata.input.abstract_grid` module encloses the classes.
N/A
5min

Create abstract grid class for model enclosed in CSV files

---

setup.cfg

Bump the version so we can do a new release. Also forgot to pin the fs version in setup.cfg.
See above
Ran `tox` in PostREISE after installing this branch.
3 min

Bump version to v0.5.3 

---

.gitignore
Pipfile
Pipfile.lock
powersimdata/input/check.py
powersimdata/input/tests/test_check.py
powersimdata/network/constants/model.py
powersimdata/network/constants/plants.py
powersimdata/network/constants/region/europe.py
powersimdata/network/constants/region/usa.py
powersimdata/network/europe_tub/model.py
powersimdata/network/helpers.py
powersimdata/network/model.py
powersimdata/network/tests/test_helpers.py
powersimdata/network/tests/test_model.py

Load a PyPSA-eur `Network` object into memory, generate model immutables for the grid model and refactor all functions mapping one area to another for a grid model or functions checking that areas or resources are part of a grid model.
* Update **Pipfile**, **Pipfile.lock** and **requirements.txt** files with new `zenodo_get` package and pinned version of `fs` (there is an issue with the most recent version as dicussed [here](https://github.com/PyFilesystem/pyfilesystem2/issues/535))
* Update **.gitignore**
* Refactor the `area_to_loadzone` function and functions checking that areas/rsources are part of a grid model
* Create model immutables for Europe
* Create a new class, `TUB`, where a …

Add PyPSA-Eur

---

powersimdata/scenario/create.py

Refactor the building phase of a scenario since we will in the near future use grid model in the form of a PyPSA `Network` object. Closes #632.
Allow to build a scenario from a PyPSA `Network` object
Existing unit tests. Especially, the `powersimdata.scenario.tests.test_create`
The `powersimdata.scenario.create` module
N/A
15 min

Refactor builder

---

powersimdata/input/abstract_grid.py
powersimdata/input/helpers.py
powersimdata/input/scenario_grid.py
powersimdata/network/csv_reader.py

Clean up the grid related modules
* Read all grid csv files in the `CSVReader` class
* Move the `csv_to_data_frame` function and rename it
* Format docstrings
Run existing unit tests
The `AbstractGrid` and the `CSVReader` classes
N/A
5min

Grid clean up 

---

powersimdata/scenario/create.py

Fix a typo.
Remove a letter.
Manually in a container.
15 sec

fix: typo in column name

---

powersimdata/scenario/ready.py

Export the `get_profile` and `get_onshore_wind` methods.
Add the `get_profile` and `get_onshore_wind` methods to the list of `exported_methods` in the `Ready` class.
Current unit tests.
In the `powersimdata.scenario.ready` module.
N/A
2min

Augment list of exported methods

---

setup.cfg

Bump version prior to release.
10 sec

chore: bump version to 0.5.4

---

.github/workflows/coverage.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml

I noticed there were new versions of the checkout and setup-python actions, so might as well upgrade.
Nothing, as far as I can tell, other than using a newer version of node.js on the action runners. There might be new features we could use, but I haven't looked closely.
The checks still pass.
1 min

ci: update action versions

---

powersimdata/scenario/move.py

Import from the correct module. This might succeed at runtime due to the function already having been imported, but that's not reliable. 
10 sec

fix: update import statement

---

powersimdata/input/const/casemat_const.py
powersimdata/input/converter/pypsa_to_grid.py
powersimdata/input/converter/tests/test_pypsa_to_grid.py

Re-enable roundtrip conversion

---

powersimdata/input/exporter/export_to_reise.py
powersimdata/input/transform_grid.py
powersimdata/scenario/execute.py

Pass a grid.pkl file as input to REISE.jl instead of case.mat. Partially addresses #668 along with https://github.com/Breakthrough-Energy/REISE.jl/pull/185
Remove `export_case_mat` which is now in REISE.jl temporarily. Preserve index names in transform_grid.py so operations on it after unpickling work as expected.
Ran a scenario in a container.
10 min

Replace case.mat with grid.pkl

---

powersimdata/input/converter/pypsa_to_grid.py

Introduce a functionality to import substations from arbitrary pypsa networks. The code is mostly aligned to the convention in pypsa-eur(-sec)
What is the larger goal of this change?
How is the purpose executed?
How did you test this change (unit/functional testing, manual testing, etc.)? 
* It's helpful to clarify where your new code lives if you moved files around or there could be confusion/
* What files are most important?
How the code can be used and/or images of any graphs, tables or other visuals (not always applicable). 
How long will it take for reviewers and observers to understand this code change?

Pypsa substations

---

.dockerignore

Update path to reflect changes to zenodo download.
Add wildcard to excluded paths
Ran a docker build and observed the size of the build context
10 sec

chore: update dockerignore

---

powersimdata/input/converter/pypsa_to_grid.py
powersimdata/input/converter/tests/test_pypsa_to_grid.py

Support conversion of hydro reservoirs with inflow time-series.
For each storage unit with an inflow time series, an artificial bus is created. There the storage unit together with a new inflow generator is located. The new bus is linked to the network via a DC line of the output capacity of the storage unit.  
Manual inspection
10 min

Support hydro inflow functionality

---

powersimdata/input/converter/pypsa_to_grid.py

Always add geo coordinates to branch and plant when importing from pypsa. 
Dicussed in the meeting
Automatic
5 min

Fix bus assignment/naming and add geographical coordinates to branch and plant 

---

powersimdata/input/converter/pypsa_to_grid.py
powersimdata/input/converter/tests/test_pypsa_to_grid.py
powersimdata/input/grid.py
powersimdata/input/tests/test_check.py
powersimdata/network/europe_tub/model.py

Add `europe_tub` as a supported model when instantiating a `Grid`
Various refactoring to support this, specifically integrating `TUB` and `FromPyPSA` so that both are fully populated. 
wip
* It's helpful to clarify where your new code lives if you moved files around or there could be confusion/
* What files are most important?
How the code can be used and/or images of any graphs, tables or other visuals (not always applicable). 
How long will it take for reviewers and observers to understand this code change?

Enable creating a grid object for europe model

---

setup.cfg

chore: bump version to 0.5.5
